<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Danielle Mirzaeian, Nahom Fisseha" />
<meta name="author" content="Faculty Research Mentor Dr. Sayed Mostafa" />
<meta name="author" content="Graduate Research Assistant Mentor Chinedu Jude Nzekwe" />

<meta name="date" content="2022-06-22" />

<title>Statistical Analysis of Fire Incidents in the City of Greensboro, NC</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Statistical Analysis of Fire Incidents in the City of Greensboro, NC</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="Report.html">Project Report</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Statistical Analysis of Fire Incidents in
the City of Greensboro, NC</h1>
<h4 class="author">Danielle Mirzaeian, Nahom Fisseha</h4>
<h4 class="author">Faculty Research Mentor Dr. Sayed Mostafa</h4>
<h4 class="author">Graduate Research Assistant Mentor Chinedu Jude
Nzekwe</h4>
<h4 class="date">2022-06-22</h4>

</div>


<div id="abstract" class="section level2">
<h2>Abstract</h2>
<p>The research in this report examines twelve years of reported fire
incidents in Greensboro, NC to further analyze how fire service response
time is affected as well as how fire service response time affects the
rate of total loss in household fires. Additionally, this report will
provide a variety of forecasting models in order to predict the future
in regards to reported fire incidents. To produce sufficient results a
variety of statistical analysis approaches have been accomplished. We
have visualized the data (univariate , bivariate, time series),
forecasted the data (TBATS, ARIMA, Holtwinters), and built linear
regression and random forest models in order to fully conquer the
research questions at task. In result, we were able to identify what
factors hold most significance in relation to response time as well as
depict to what extent response time affects total loss. In addition we
produced multiple forecasting models in order to accurately predict the
future of reported fire incidents in Greensboro, NC.</p>
</div>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>Many calls are made to fire departments all the time. Whether it is a
false alarm or not, it is important for first responders to take care of
fire incidents as soon as possible. Therefore it is important to look at
data about different fire incidents and see how the response time can be
improved for all kinds of situations.</p>
<p>There are all kinds of fire incidents, some not even about fires. For
example someone could be having a stroke and the local fire department
was called to take action on the situation. If the incident is a fire,
it could be at all kinds of different properties. Some different
properties are small houses, apartment buildings, and highways. The fire
could vary in size, like the wildfires in California.</p>
<p>No matter the type of fire incident. It is vital that first
responders attend to the situation quickly. Now, there can be some
factors that can affect the response time of the first responders. Some
of those factors are the location, the type of property, and the type of
the incident. From this project we want to explore which factors from
the data have a significant affect on the response time of the fire
department. By learning about these factors, the fire department could
use this information to work on decreasing their response time.</p>
<p>For more than ten years, the city of Greensboro, NC has been
collecting data on fire incidents in their area. Some of this data
includes the date of the incident, the response time, the location, and
the type of property. Yet, take note when looking at the data that it
goes from July 1, 2010, to May 31, 2022. So for the years 2010 and 2022,
only data for about half of those years was collected.</p>
<p>For this project we will be visualizing the fire incidents in
Greensboro, NC. Our research questions are 1) What factors affect the
response time to fire incidents? 2) How to improve the response time? 3)
How does response time by fire emergency services affect the rate of
total loss and civilian injuries? 4)Can we build models to forecast the
number of fire incidents in certain areas of Greensboro based on the
data from 2010 to 2022? 5) What Dynamic models can we make for
forecasting fire incidents?</p>
</div>
<div id="related-literature" class="section level2">
<h2>Related Literature</h2>
<p>Prior to beginning this study we sought to obtain as much knowledge
from previous similar reports as possible. In this process we were able
to acquire multiple different reports from a variety of similar topics
ranging from observing response time to forecasting mass fires . With
this, each report had its own distinct way of coming to a solution.</p>
<p>To begin our review of previous reports we first analyzed several
reports regarding the observation of response time. In a report that
analyzed fire service response time by Aleisa and Savsar (2014), they
wanted to create a discrete event simulation that reduces the response
time to fire incidents to below five minutes. It was concluded that with
the introduction of centralized systems and navigation technology
response time was able to be reduced by 32%. Buffington and Ezekoye
(2018) did a research project about analyzing the relationship between
fire service response times and fire outcomes. While using the NFIRS
dataset they were able to conclude that on average, increasing response
times are linked to increasing monetary losses at a rate of about 3000
USD per minute for the interval between 3-13min. Similarly, Neil
Challands (2010) also wrote a paper analyzing the same relationship. He
used plots of various types to analyze the different types of fires and
their relationship to response time. He found that response time
significantly affects the amount of structural damage. In another report
written by KC and Corcoran (2017) they looked at how spatial patterns of
residential fire incidents affect response time and what factors explain
those spatial patterns. In their modeling they looked at 12 variables.
Some of those are Winter(Incidents during the winter), socioeconomic
disadvantage, street connectivity, and fire station distance. They found
that response time tends to increase from factors like winter weather,
places with high numbers of children and low socioeconomic households.
Most importantly, their results showed that low street connectivity had
the biggest impact on response time. In addition, some students from
Vanderbilt University (2017) wanted to solve the problem of having
efficient response time for highly populated areas. They approached this
by creating a non-linear mathematical program that optimized the
expected incident coverage and proposing an algorithmic framework to
solve the issue.</p>
<p>We then continued to review previous reports in regards to
forecasting fires. Similar to our approach we found a group of students
from the Data Science program at the University of San Francisco (2019)
who were able to use linear regression in machine learning to predict
and analyze response times for the San Francisco Fire Department.
Another report written by Li, Zhang, and Fu (2022) they wanted to learn
how to use drones to monitor and eliminate forest fire incidents in
Victoria. One thing they did in this paper that is related to a part of
our research was building a forecasting model that predicted the
following 10 years of forest fires in Australia through K-means
clustering algorithms and time series forecasting (SARIMA). With that
information from the time series forecasting, they estimated the
increase in the expense of one drone over ten years.</p>
<p>Although multiple studies have sought to capture the analytics behind
many different aspects in regards to fire incidents, not many have gone
completely in-depth in terms of covering fully what factors can affect a
given fire department in terms of fire service response time. In this
report we aim to completely cover all given factors that may affect fire
service response time and how response time affects the rate of total
loss in Greensboro, NC. Additionally, to help the Greensboro Fire
Department be better prepared for dealing with future fire incidents in
the city, we will build a variety of models to forecast the future daily
and weekly number of fire incidents in the city.</p>
</div>
<div id="data-methods-and-analysis" class="section level2">
<h2>Data, Methods, and Analysis</h2>
<div id="data" class="section level3">
<h3>Data</h3>
<p>For this analysis, we utilized public data from the Greensboro Fire
Department. This data set accounts for all reported fire incidents in
the city of Greensboro and updates itself continuously. Although, we
noticed there were some missing values in the data. So we did a map to
check the percentage of missing values and it ended being about 14
percent for the whole data set. To further cater towards our research we
filtered the data set in two areas; the date (from July 1, 2010 to May
31st, 2022) and the Property Use (“1-2 family dwelling”). In addition to
this we converted ResponseTime to seconds. The initial data set can be
found at this website link:<a
href="https://data.greensboro-nc.gov/datasets/greensboro-fire-incidents/explore"
class="uri">https://data.greensboro-nc.gov/datasets/greensboro-fire-incidents/explore</a></p>
</div>
<div id="methods" class="section level3">
<h3>Methods</h3>
<div id="exploratory-data-analysis" class="section level4">
<h4>Exploratory Data Analysis</h4>
<p>The first step in our research project was exploratory data analysis.
During this process we investigated the data looking for patterns and
outliers. This was carried out by making various graphical
representations of the data.</p>
</div>
<div id="univariate-explorations" class="section level4">
<h4>Univariate Explorations</h4>
<p>Data Visualizations consisting of one variable</p>
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>For the histogram above, we learned that the typical response time
falls between about 100 seconds to 400 seconds and that the distribution
is normal.</p>
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>From the histogram above, we can visually see the distribution of the
amount of staff members reported towards a given incident. It is
important to note that the Y-axis on this graph has been scaled.
Overall, the great majority of total stall on incident is 4.</p>
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>For the graph above, we can identify that there are not many
occasions in which civilians have reported injured. There has only been
two incidents in which two or more civilian injuries occurred. It is
important to note that the Y-axis on this graph has been scaled.
Overall, the great majority of civilian injuries is 0.</p>
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>For the graph above, we can identify that there has only been a
couple incidents in which fatalities have been reported in regards to
civilians. It is important to note that the Y-axis on this graph has
been scaled. Overall, the great majority of civilian fatalities is
0.</p>
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>For the graph above, we can identify that there has only been a
handful of incidents in which injuries have been reported in regards to
fire service respondents. It is important to note that the Y-axis on
this graph has been scaled. Overall, the great majority of fire service
injuries is 0.</p>
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The histogram above displays the amount of property loss across the
amount of incidents reported.</p>
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The histogram above displays the amount of total loss (property +
content) across the amount of incidents reported.</p>
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>From this bar graph, it can be seen that the frequency of calls to
the fire stations are less during the middle of the night and increase
as people start waking up.</p>
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>For this graph, we wanted to find out which fire stations got the
most calls. Note that the calls counted are from July 1, 2010 to Jun 1,
2022. From the results we can tell that the top five fire stations that
got the most calls over ten years in Greensboro NC, was 7, 8, 14, 4, and
56.</p>
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>For this bar plot, we wanted to find out which fire districts got the
most calls in Greensboro, NC over ten years. The fire districts consist
of a few fire stations. The most popular fire districts from this bar
plot from greatest to least were Battalion II, Battalion I and Battalion
III.</p>
<p><img src="index_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>From this graph, we wanted to learn if there were some years that had
a significant difference in number of phone calls to the fire stations
in Greensboro, NC. By looking at those differences we could explore how
response time varied between years that were busier than others. Note
from this graph, that only half of the data was collected for the years
2010 and 2022, so those bars will be obviously lower than the bars of
other years displayed in the graph.</p>
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>This visual was created to look at if the number of calls to the fire
station would vary depending on which shift was currently working. For
this data, there were three shifts, A, B, and C. From the results, it
can be seen that there is no obvious difference in the frequency of the
calls to the fire station on different work shifts.</p>
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>From this bar graph, it can be seen that the frequency of calls to
the fire station over ten years ended up being about the same between
each day of the week with no obvious differences.</p>
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>From the bar plot above, it is shown that the first week and the last
week of the year typically had fewer calls to the fire station compared
to other weeks in the year. This graph had a little more variability in
frequency in calls. For example, the dip in the middle of the bar plot.
This plot helps us to look at the busier times in the data and compare
the response times.</p>
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>This visual was used to look further into if there was a higher
frequency of calls to fire stations in certain parts of the year. From
the results, June and February seem to have the lowest frequency of
calls, while January and December have the highest frequency of calls.
With this knowledge we can look at how response time varied with those
months.</p>
</div>
<div id="bivariate-explorations" class="section level4">
<h4>Bivariate Explorations</h4>
<p>Data Visualizations of a given variable vs response time</p>
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>From this box plot, we wanted to see if certain weeks would have
notable differences in response time. Looking at the results, there does
not seem to be much variation. Therefore, the weeks in the year might
not have a significant impact on response time.</p>
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>The box plot above shows that there is a lot of variability in
response time depending on which station responded to the call. By
looking at these results, we can explore and question why different fire
stations have such big contrasts in response time.</p>
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>For this graph above, we looked at nature code and how it affects
response time. Nature code represents the nature of the fire incident,
whether it was a fire or someone having a stroke. As shown by the graph,
there is a lot of variability in response time depending on the nature
of the fire incident.</p>
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>From this scatter plot, we wanted to see if the number of staff on
incident would affect the response time of the fire responders. The
outcome of the graph shows that there is no significant change in
response time when having more people on shift. The response time still
falls between 100 and 600 seconds, no matter the number of
responders.</p>
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>From the scatter plot above, we wanted to visualize the relationship
between response time and property loss. Through this we were able to
identify a very slight correlation between the two. The majority of the
higher property loss values fall between 100 and 400 seconds</p>
<p><img src="index_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>From the scatter plot above, we wanted to visualize the relationship
between response time and total loss. Through this we were able to
identify a very slight correlation between the two. Similar to property
loss, the majority of the higher total loss values fall between 100 and
400 seconds.</p>
<p>Below, the box and violin plots had similar results to the bar graphs
presented earlier. Each graph will summarize briefly what have seen
before.</p>
<p><img src="index_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>For this violin and box plot, it can be seen that there is very
little difference in response time between the days of the week.</p>
<p><img src="index_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>From the plot above there is a slight increase in the average
response time after the year 2013 and it continues to stay the same or
slightly increase more.</p>
<p><img src="index_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>For this graph it can be seen that different work shifts did not
affect the response time.</p>
<p><img src="index_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>As shown by the graph, the response time varies depending on which
fire district responded to the fire incident.</p>
<p><img src="index_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>For this box and violin plot, we learned that the time of month in
the year has very little effect on the response time.</p>
<p><img src="index_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>From this visual, we learned that alarm hour has a slight effect on
response time, as shown by the dips in the plot.</p>
<p><img src="index_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>For the graph above, there would sometimes be a couple alarms set off
for a fire incident, but it did not affect the response time whether the
alarm was once or twice.</p>
<p><img src="index_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>For the graph above, we can see the how each level of civilian injury
various in relations to response time.</p>
<p><img src="index_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>For the graph above, we can see the how each level of civilian
fatality various in relations to response time.</p>
<p><img src="index_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>For the graph above, we can see the how each level of fire service
injury various in relations to response time.</p>
</div>
</div>
<div id="time-series-visualization" class="section level3">
<h3>Time Series Visualization</h3>
<p>This section contains the visualization of all the data of the fire
incidents in Greensboro, NC from July 1, 2010 to May 31, 2022.</p>
<div id="daily-time-series" class="section level4">
<h4>Daily Time series</h4>
<p><img src="index_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>Above is a time series plot of the daily number of fire incidents
from July 1, 2010 to June 1st 2022. As shown by the plot, there were big
spikes around 2014, 2018, and 2021.</p>
<p>To take a deeper look into the time series below is the daily time
series graphs for the years 2010 to 2022.</p>
<p><img src="index_files/figure-html/unnamed-chunk-42-1.png" width="1728" /></p>
<p>Above is the time series of the daily fire incidents broken into
plots by year. From these graphs we have a clearer view of peaks for
each year. So from the results, we can see that there were major peeks
around April 2011, March 2014, October 2018, and February 2021.</p>
</div>
<div id="monthly-time-series" class="section level4">
<h4>Monthly Time Series</h4>
<p><img src="index_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>Above is a time series graph depicting the number of monthly fire
incidents from July 1, 2010 to May 31 2022. The graph shows an upward
trend but with drastic drops occurring at dates like November of 2019
and November 2021.</p>
</div>
</div>
</div>
<div id="results" class="section level2">
<h2>Results</h2>
<div id="time-series-forecasting" class="section level3">
<h3>Time Series Forecasting</h3>
<div id="daily-number-of-fire-incidents-from-2010-to-2022"
class="section level4">
<h4>Daily number of fire incidents from 2010 to 2022</h4>
<p>In order to forecast the data we had to convert it into time series
objects with the ts function in R studio.</p>
<p>Before forecasting we checked the data for stationarity. Meaning that
we are checking that the time series has a constant mean and variance
over time.</p>
<p>To check if the data needs any first difference calculations then we
used the ndiffs function. Also to check if there needs to be any
seasonal difference calculations then we used the nsdiffs function.</p>
<pre class="r"><code>#determine the number of differences required for time series to be made stationary
ndiffs(gso.fire.ts.2) #1</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>nsdiffs(gso.fire.ts.2) #0</code></pre>
<pre><code>## [1] 0</code></pre>
<p>From the results, the data needs one difference, so we used the diff
function to do that.</p>
<p>Using the acf function we check that the data is stationary after we
had done the first difference for the data.</p>
<pre class="r"><code>#attempt at differencing
gso.fire.ts.2.dif = diff(gso.fire.ts.2)
#checking stationarity of first difference
acf(gso.fire.ts.2.dif)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>Using the acf function we made sure that it did not take many lags to
hit 0. From the results, the first difference made our data
stationary.</p>
<p><img src="index_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>The plot above shows the daily time series graph before and after the
first difference was calculated.</p>
<p>After checking for stationarity we could begin forecasting.</p>
<p><img src="index_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<pre><code>##                     ME     RMSE      MAE MPE MAPE      MASE        ACF1
## Training set -0.112468 6.553429 4.981169 NaN  Inf 0.4296495 0.001337923</code></pre>
<p>We used the Exponential smoothing state space model with Box-Cox
transformation, ARMA errors, Trend and Seasonal components (TBATS model)
because it is a popular model that tends to perform well at forecasting
time series.</p>
<p>For the plot above, we used the whole data set, from July 1, 2010 to
May 31, 2022. We planned to forecast the fire incidents from June 1,
2010 to December 31, 2022. From the plot we can see that the TBATS was
doing well, it seemed to predict a slow big dip that would eventually
start going up again before 2022 ended. The dip though seems to go below
the average at one point.</p>
<p><img src="index_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<pre><code>##                      ME     RMSE      MAE       MPE    MAPE      MASE
## Training set 0.07291525 6.507242 4.929365 -4.066674 16.8887 0.6931919
##                       ACF1
## Training set -0.0002287735</code></pre>
<p>We also chose the Autoregressive Integrated Moving Average (ARIMA)
model because it has been known to perform competently. Compared to the
TBATS model, the ARIMA automatically calculates the differences, so
those don’t have to be done manually.</p>
<p>For the plot above, there was a slight increase briefly and then
after that the forecast created a horizontal line. The horizontal line
appears to be close to the average line of the data.</p>
<p><img src="index_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<pre><code>##                      ME     RMSE      MAE MPE MAPE      MASE        ACF1
## Training set -0.1338178 6.518173 4.943409 NaN  Inf 0.4280165 0.001781049</code></pre>
<p>In the plot above we can see that the TBATS model(light red) did not
follow the true number of fire incidents(light blue). This appears to be
because the data end three months earlier at March 1, 2022 to see how
the predictions would appear. So around that time period there were some
drastic drops in number of fire incidents which led to the TBATS model
forecasting such a severe drop in incidents.</p>
<p><img src="index_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<pre><code>##                     ME     RMSE      MAE       MPE     MAPE      MASE
## Training set 0.0767143 6.502043 4.919923 -4.048972 16.86875 0.6907802
##                       ACF1
## Training set -0.0001927383</code></pre>
<p>From the plot above, there was an increase briefly and then the
forecast created a horizontal line. Plus, the horizontal line appears to
be close to the average line of the data. So when ended the data set
three months earlier the ARIMA model did better than the TBATS for
predicting number of future fire incidents.</p>
</div>
<div id="monthly-number-of-fire-incidents-from-2010-to-2022"
class="section level4">
<h4>Monthly number of fire incidents from 2010 to 2022</h4>
<p>We again converted the data into a time series object us the ts
function in order to use the functions for forecasting the time series
data.</p>
<p>Then we checked the monthly data for stationarity.</p>
<p>We used the ndiffs and nsdiffs functions for checking if a first
difference or seasonal difference had to be calculated</p>
<pre class="r"><code>ndiffs(gso.fire.ts.2) #1</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>nsdiffs(gso.fire.ts.2) #0</code></pre>
<pre><code>## [1] 0</code></pre>
<p>So, our data needs one first difference and that is done with the
diff function. After that, we used the acf function to make sure that
the difference transformation made our data stationary.</p>
<p><img src="index_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>Using the acf function again we made sure that it did not take many
lags to hit 0. From the results, the first difference made our data
stationary.</p>
<p><img src="index_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>The plot above shows the monthly time series graph before and after
the first difference was calculated.</p>
<p>Now that the monthly data is stationary we can being forecasting.</p>
<p><img src="index_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<pre><code>##                     ME     RMSE      MAE  MPE MAPE      MASE        ACF1
## Training set -4.171551 56.04023 43.91867 -Inf  Inf 0.3824204 -0.02345482</code></pre>
<p>From the time series plot above, the TBATS model (red line) shows an
increase for the future number of fire incidents. The line appears to
fit fairly well with the trend of the data.</p>
<p><img src="index_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<pre><code>##                    ME     RMSE      MAE       MPE     MAPE      MASE       ACF1
## Training set 6.008386 66.80605 49.59427 0.2636763 5.173699 0.6704695 -0.0142654</code></pre>
<p>In the plot above, it can be seen that the ARIMA model was producing
similar spikes compared to the TBATS model and had done a fairly good
job.</p>
<p><img src="index_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<pre><code>##                     ME     RMSE      MAE  MPE MAPE      MASE       ACF1
## Training set -5.423912 81.16663 60.75395 -Inf  Inf 0.7440428 -0.5099868</code></pre>
<p>As seen above, the HoltWinters model predicted much larger spikes
upwards compared to the TBATS model. As a result, with such a drastic
increase it is likely it would be less accurate than the TBATS model for
this data.</p>
</div>
</div>
</div>
<div id="multi-step-forecasting" class="section level2">
<h2>Multi-Step Forecasting</h2>
<p><img src="index_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<pre><code>##                     ME    RMSE      MAE  MPE MAPE      MASE         ACF1
## Training set -0.593745 7.71444 5.982271 -Inf  Inf 0.4312064 -0.005924354</code></pre>
<p>For the plot above, the data was split into a training set and a test
set. The training set was from July 1, 2010 to December 31, 2022. The
test set was from January 1, 2022 to May 31, 2022. The results show that
the TBATS model did fairly well, but it did not follow the big dip in
the true data.</p>
<p>From the accuracy function, we can see that the errors of the TBATS
model were small. The root mean square error was only 7.71.</p>
<p><img src="index_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<pre><code>##                         ME     RMSE      MAE       MPE     MAPE      MASE
## Training set -2.836533e-13 7.793247 5.969387 -6.113375 19.90425 0.7813334
##                   ACF1
## Training set 0.2085914</code></pre>
<p>From the visual above, the data was again split into a training set
and a test set. The training set was from July 1, 2010 to December 31,
2022. The test set was from January 1, 2022 to May 31, 2022. With the
results of th plot and the accuracy function, the ARIMA model did fairly
and had a root mean square error of only 7.79.</p>
<p><img src="index_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<pre><code>##       ARIMA       TBATS Combination 
##    8.853813   19.038254    9.176881</code></pre>
<p>As can be seen above, the data was split into training and test sets
with the same dates as the two previous plots. From the results it can
be seen that the TBATS model did not do that well and predicted a bigger
decrease than what actually happened with the actual data.</p>
<p>From the accuracy function, we can see that the ARIMA and Combination
models did better</p>
<p><img src="index_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<pre><code>##                     ME     RMSE      MAE      MPE     MAPE      MASE       ACF1
## Training set 0.7417519 170.9214 133.6995 123.8174 123.8174 0.5040507 -0.4291488</code></pre>
<p>For this plot, it can be seen that the TBATS model did not expect
such a big dip in the true data but it still predicted values that
appear to fit well with the plot.</p>
<p>From the accuracy function, we had a root mean squared error of
170.92, which is pretty high but that is because of the big dip in the
true data that the TBATS model was not able to predict.</p>
<p><img src="index_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<pre><code>##                        ME     RMSE   MAE       MPE     MAPE      MASE
## Training set 1.364256e-13 114.6902 93.28 -1.371908 9.592816 0.6410997
##                    ACF1
## Training set -0.3627437</code></pre>
<p>As you can see, the ARIMA model had the same issue as the TBATS model
with the big dip in the true data.</p>
<p>The root mean squared error for this model ended up being 114.69,
which is pretty high.</p>
<p><img src="index_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<pre><code>##                 ME     RMSE      MAE       MPE     MAPE       ACF1 Theil&#39;s U
## Test set -27.91337 134.5553 99.61927 -4.403427 10.79837 -0.4022097 0.6941563</code></pre>
<p>For the model above it can been seen that the HoltWinters method was
also not able to predict the big dip in the true data, but what it did
predict followed the trend of the data nicely.</p>
<p>From the accuracy function, the root mean squared error was 134.55,
which is significantly high.</p>
<p><img src="index_files/figure-html/unnamed-chunk-76-1.png" width="672" /></p>
<pre><code>##       ARIMA       TBATS          HW Combination 
##   110.67193    79.13765    55.57372    76.41376</code></pre>
<p>As shown by the plot above, the models were unable to predict the big
dip in the true data that happened in 2020. But all the models followed
the trend of the data fairly well.</p>
<p>From the accuracy function the root mean squared error for ARIMA was
110.67, TBATS’ was 79.14, HoltWinters’ was 55.57, and the Combination
model’s was 76.41. All were fairly high because of the huge drop in the
true data.</p>
</div>
<div id="modeling-of-response-time" class="section level2">
<h2>Modeling of Response Time</h2>
<p>In this section the results of the predictive modeling of fire
incidents is displayed.</p>
<p>There were two types of modeling done, linear regression and random
forest. With this, we can evaluate the main factors that affect response
time for fire incidents.</p>
<div id="linear-regression" class="section level3">
<h3>Linear Regression</h3>
<p>In order to successfully depict the affect of each given variable in
relation to response time the first model we sought was a Linear
Regression model. With this approach we are able to identify which
surrounding variables from our original data set directly impact our
independent variable which in this case is fire service response time.
First we filtered our cutoff point in regards to response time and ran a
linear regression model with all given variables that we identified to
have a direct impact on response time. Then we used two different
variable selection methods to finalize the surrounding dependent
variables being used in the Linear Regression model Once we completed
the variable selection process we were able to identify that the
variables holding significance in correlation to response time were
TotalStaffOnIncident, FireDistrict, DayOfWeek, shift, Month, AlarmHour,
and NatureCode. When originally running this test a couple of our
dependent variables had processed as one big character component not
giving the model its true ability to compare all given components within
that given variable. To solve this we mutated these variables as factors
in order to unravel the different contents within each variables
allowing the model to accurately compare each given variable to fire
service response time. In return we were able to mathematically see the
significance of each variable and its impact on response time as a
whole.</p>
<p>First we created a linear regression model on all given variables
that directly impact response time.</p>
<pre><code>## 
## Call:
## lm(formula = response_time_seconds ~ TotalStaffOnIncident + FireDistrict + 
##     DayOfWeek + shift + Month + AlarmTime + NatureCode, data = gso.fire.filtered)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -340.43  -47.60   -6.53   40.29  383.81 
## 
## Coefficients:
##                                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                           408.9655    45.3873   9.011  &lt; 2e-16 ***
## TotalStaffOnIncident                    0.9030     0.1409   6.410 1.46e-10 ***
## FireDistrictBattalion I              -147.1994    14.6499 -10.048  &lt; 2e-16 ***
## FireDistrictBattalion II             -168.3688    14.6493 -11.493  &lt; 2e-16 ***
## FireDistrictBattalion III            -136.0269    14.6590  -9.279  &lt; 2e-16 ***
## FireDistrictBattalion IV             -135.2603    14.6599  -9.227  &lt; 2e-16 ***
## FireDistrictBattalion V              -140.2406    14.6571  -9.568  &lt; 2e-16 ***
## FireDistrictColfax                     43.1908    36.3430   1.188 0.234670    
## FireDistrictFire District 13          -75.2848    15.9148  -4.731 2.24e-06 ***
## FireDistrictFire District 14          -72.6721    14.7392  -4.931 8.21e-07 ***
## FireDistrictGuilford  College        -158.4621    15.6616 -10.118  &lt; 2e-16 ***
## FireDistrictHigh Point Fire District -163.8343    42.3830  -3.866 0.000111 ***
## FireDistrictMcLeansville             -116.1506    17.8435  -6.509 7.57e-11 ***
## FireDistrictNortheast Fire            197.9903    75.8371   2.611 0.009036 ** 
## FireDistrictOak Ridge Fire Dept       -48.9577    33.7024  -1.453 0.146324    
## FireDistrictOther Protection Agency    82.9478    75.8323   1.094 0.274031    
## FireDistrictPinecroft Sedgefield      -88.8137    17.3627  -5.115 3.14e-07 ***
## FireDistrictPleasant Garden            -3.0358    22.8157  -0.133 0.894149    
## FireDistrictPTI Airport               -70.8423    75.8393  -0.934 0.350248    
## FireDistrictSummerfield                27.2998    21.2993   1.282 0.199942    
## FireDistrictWhitsett Fire District     62.2344    75.8355   0.821 0.411847    
## DayOfWeekMonday                        -0.2482     0.7727  -0.321 0.748055    
## DayOfWeekSaturday                      -2.3148     0.7737  -2.992 0.002774 ** 
## DayOfWeekSunday                        -4.0342     0.7723  -5.224 1.76e-07 ***
## DayOfWeekThursday                      -0.2812     0.7799  -0.361 0.718390    
## DayOfWeekTuesday                        0.1089     0.7763   0.140 0.888393    
## DayOfWeekWednesday                     -0.1706     0.7817  -0.218 0.827270    
## shiftB                                  2.5005     0.5063   4.939 7.86e-07 ***
## shiftC                                 -0.6240     0.5058  -1.234 0.217346    
## Month02                                -5.6342     1.0059  -5.601 2.13e-08 ***
## Month03                                -7.6323     0.9891  -7.717 1.20e-14 ***
## Month04                                -6.3495     0.9981  -6.361 2.00e-10 ***
## Month05                                -7.5836     0.9854  -7.696 1.41e-14 ***
## Month06                                -7.5963     1.0216  -7.436 1.05e-13 ***
## Month07                                -8.5329     0.9951  -8.575  &lt; 2e-16 ***
## Month08                                -7.2737     0.9915  -7.336 2.21e-13 ***
## Month09                                -7.4497     0.9959  -7.481 7.44e-14 ***
## Month10                                -5.7232     0.9860  -5.805 6.46e-09 ***
## Month11                                -5.1842     0.9944  -5.214 1.86e-07 ***
## Month12                                -5.2021     0.9749  -5.336 9.52e-08 ***
## AlarmTime12-17                        -49.9845     0.6514 -76.738  &lt; 2e-16 ***
## AlarmTime18-23                        -40.1459     0.6528 -61.502  &lt; 2e-16 ***
## AlarmTime6-11                         -41.2591     0.6701 -61.572  &lt; 2e-16 ***
## NatureCode50MAJ                        -7.7294    56.8312  -0.136 0.891816    
## NatureCode50MCI1                       27.0040    85.9155   0.314 0.753287    
## NatureCode50PD                         45.0858    44.2582   1.019 0.308347    
## NatureCode50PI                         11.7468    43.1613   0.272 0.785498    
## NatureCode50PIN                         6.9150    50.3770   0.137 0.890822    
## NatureCode50VOT                        43.8551    67.9249   0.646 0.518513    
## NatureCodeABDOM                        26.3874    42.9878   0.614 0.539326    
## NatureCodeACHRPD                       60.0472    46.2310   1.299 0.193998    
## NatureCodeACHRPI                       49.6325    46.2311   1.074 0.283015    
## NatureCodeALLERG                       23.6859    43.0192   0.551 0.581917    
## NatureCodeANBITE                       11.7936    43.4519   0.271 0.786071    
## NatureCodeASSLT                        22.2219    43.0910   0.516 0.606066    
## NatureCodeBCKPN                        34.2506    43.0908   0.795 0.426703    
## NatureCodeBLEED                        22.0207    42.9813   0.512 0.608419    
## NatureCodeBREATH                       20.7730    42.9697   0.483 0.628789    
## NatureCodeBRUSH                        48.3069    43.6321   1.107 0.268235    
## NatureCodeBURN                         24.7300    43.6683   0.566 0.571181    
## NatureCodeCARDIA                       11.0232    42.9896   0.256 0.797631    
## NatureCodeCHEST                        21.0846    42.9715   0.491 0.623664    
## NatureCodeCHOKE                        16.0340    43.0508   0.372 0.709562    
## NatureCodeCOALRM                      119.6694    43.0211   2.782 0.005409 ** 
## NatureCodeCODVIO                       73.9665    67.9347   1.089 0.276250    
## NatureCodeCONFIN                       29.0330    43.6706   0.665 0.506169    
## NatureCodeDIABET                       16.4890    42.9818   0.384 0.701256    
## NatureCodeDROWN                        10.8063    60.7568   0.178 0.858832    
## NatureCodeEHAZ                         46.7907    43.0476   1.087 0.277060    
## NatureCodeELEC                        -12.2493    45.5716  -0.269 0.788089    
## NatureCodeELEV                        -48.5650    48.4698  -1.002 0.316363    
## NatureCodeEXPLO                        15.8532    44.0853   0.360 0.719145    
## NatureCodeEXPOS                        14.7874    44.0274   0.336 0.736971    
## NatureCodeEXTRI                        -7.2951    46.2297  -0.158 0.874614    
## NatureCodeEYE                          28.6906    48.9859   0.586 0.558084    
## NatureCodeFALL                         31.8106    42.9782   0.740 0.459206    
## NatureCodeFALLFO                       75.4685    43.2777   1.744 0.081192 .  
## NatureCodeFIRAL                        38.2288    42.9653   0.890 0.373596    
## NatureCodeFIRAST                       46.0743    43.0613   1.070 0.284635    
## NatureCodeFIRINS                     -189.2691    85.9246  -2.203 0.027615 *  
## NatureCodeFIRINV                     -107.5676    43.9085  -2.450 0.014294 *  
## NatureCodeFSERV                        88.0140    85.9199   1.024 0.305661    
## NatureCodeFUELSP                       36.5523    43.6190   0.838 0.402038    
## NatureCodeGAS                          36.8301    43.0052   0.856 0.391773    
## NatureCodeHAR                           5.3311    50.3750   0.106 0.915719    
## NatureCodeHAZ                          41.3331    44.4666   0.930 0.352615    
## NatureCodeHAZMAT                       43.4820    43.9721   0.989 0.322736    
## NatureCodeHEAD                         22.4047    43.0229   0.521 0.602534    
## NatureCodeHEART                        21.1062    42.9918   0.491 0.623472    
## NatureCodeINACC                        26.2219    45.6769   0.574 0.565920    
## NatureCodeINVES                      -120.4648    45.8054  -2.630 0.008541 ** 
## NatureCodeLIGHT                       108.4958    45.6771   2.375 0.017537 *  
## NatureCodeMED                          16.8593    43.1383   0.391 0.695931    
## NatureCodeMEDALM                       57.5180    43.4639   1.323 0.185721    
## NatureCodeMEDEM                        14.2228    43.0287   0.331 0.740990    
## NatureCodeMEDNE                        33.8170    85.9202   0.394 0.693887    
## NatureCodeMUTUAL                      -17.8019    70.7769  -0.252 0.801411    
## NatureCodeNORESP                     -103.4574    67.9310  -1.523 0.127767    
## NatureCodeODOR                         16.5666    43.1954   0.384 0.701331    
## NatureCodeOSFIR                        29.2011    43.0088   0.679 0.497167    
## NatureCodeOVDOSE                       23.8240    42.9877   0.554 0.579439    
## NatureCodePREG                         20.6101    43.0197   0.479 0.631880    
## NatureCodePSYCH                        31.0813    43.1266   0.721 0.471096    
## NatureCodeSEIZUR                       18.4210    42.9777   0.429 0.668202    
## NatureCodeSERV                         29.4488    42.9892   0.685 0.493328    
## NatureCodeSICK                         21.5386    42.9721   0.501 0.616215    
## NatureCodeSMOKE                        31.7279    43.1991   0.734 0.462671    
## NatureCodeSTAB                         25.4310    43.0629   0.591 0.554820    
## NatureCodeSTRINJ                       -2.1027    49.6544  -0.042 0.966223    
## NatureCodeSTROKE                       20.8259    42.9779   0.485 0.627981    
## NatureCodeSTRTRP                        4.8910    45.2669   0.108 0.913958    
## NatureCodeSTRUC                        -2.0314    43.0133  -0.047 0.962332    
## NatureCodeTRAUM                        26.2160    43.1103   0.608 0.543112    
## NatureCodeTSUI                         14.0629    43.7729   0.321 0.748007    
## NatureCodeUNCON                        20.7339    42.9724   0.482 0.629456    
## NatureCodeUNKNFO                       66.8186    49.6103   1.347 0.178025    
## NatureCodeUNKNWN                       16.4417    43.0290   0.382 0.702383    
## NatureCodeVFIRE                        20.0373    44.0782   0.455 0.649409    
## NatureCodeWATER                       -86.4962    67.9272  -1.273 0.202890    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 74.4 on 130053 degrees of freedom
##   (4 observations deleted due to missingness)
## Multiple R-squared:  0.1166, Adjusted R-squared:  0.1158 
## F-statistic: 145.5 on 118 and 130053 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>From the model above we are able to identify how each variable holds
significance in terms of their impact on response time. We are also able
to see which components inside each given variable hold impact and how
much using the P-Value produced from the model.</p>
<p>Then we used the stepwise regression for our first method of variable
selection.</p>
<pre><code>## Start:  AIC=1122051
## response_time_seconds ~ TotalStaffOnIncident + FireDistrict + 
##     DayOfWeek + shift + Month + AlarmTime + NatureCode
## 
##                        Df Sum of Sq       RSS     AIC
## &lt;none&gt;                              719839931 1122051
## - DayOfWeek             6    281067 720120999 1122090
## - shift                 2    237672 720077603 1122090
## - TotalStaffOnIncident  1    227388 720067319 1122090
## - Month                11    627583 720467514 1122142
## - NatureCode           76  21137791 740977722 1125666
## - AlarmTime             3  34467031 754306963 1128133
## - FireDistrict         19  37785762 757625693 1128673</code></pre>
<pre><code>## 
## Call:
## lm(formula = response_time_seconds ~ TotalStaffOnIncident + FireDistrict + 
##     DayOfWeek + shift + Month + AlarmTime + NatureCode, data = gso.fire.filtered)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -340.43  -47.60   -6.53   40.29  383.81 
## 
## Coefficients:
##                                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                           408.9655    45.3873   9.011  &lt; 2e-16 ***
## TotalStaffOnIncident                    0.9030     0.1409   6.410 1.46e-10 ***
## FireDistrictBattalion I              -147.1994    14.6499 -10.048  &lt; 2e-16 ***
## FireDistrictBattalion II             -168.3688    14.6493 -11.493  &lt; 2e-16 ***
## FireDistrictBattalion III            -136.0269    14.6590  -9.279  &lt; 2e-16 ***
## FireDistrictBattalion IV             -135.2603    14.6599  -9.227  &lt; 2e-16 ***
## FireDistrictBattalion V              -140.2406    14.6571  -9.568  &lt; 2e-16 ***
## FireDistrictColfax                     43.1908    36.3430   1.188 0.234670    
## FireDistrictFire District 13          -75.2848    15.9148  -4.731 2.24e-06 ***
## FireDistrictFire District 14          -72.6721    14.7392  -4.931 8.21e-07 ***
## FireDistrictGuilford  College        -158.4621    15.6616 -10.118  &lt; 2e-16 ***
## FireDistrictHigh Point Fire District -163.8343    42.3830  -3.866 0.000111 ***
## FireDistrictMcLeansville             -116.1506    17.8435  -6.509 7.57e-11 ***
## FireDistrictNortheast Fire            197.9903    75.8371   2.611 0.009036 ** 
## FireDistrictOak Ridge Fire Dept       -48.9577    33.7024  -1.453 0.146324    
## FireDistrictOther Protection Agency    82.9478    75.8323   1.094 0.274031    
## FireDistrictPinecroft Sedgefield      -88.8137    17.3627  -5.115 3.14e-07 ***
## FireDistrictPleasant Garden            -3.0358    22.8157  -0.133 0.894149    
## FireDistrictPTI Airport               -70.8423    75.8393  -0.934 0.350248    
## FireDistrictSummerfield                27.2998    21.2993   1.282 0.199942    
## FireDistrictWhitsett Fire District     62.2344    75.8355   0.821 0.411847    
## DayOfWeekMonday                        -0.2482     0.7727  -0.321 0.748055    
## DayOfWeekSaturday                      -2.3148     0.7737  -2.992 0.002774 ** 
## DayOfWeekSunday                        -4.0342     0.7723  -5.224 1.76e-07 ***
## DayOfWeekThursday                      -0.2812     0.7799  -0.361 0.718390    
## DayOfWeekTuesday                        0.1089     0.7763   0.140 0.888393    
## DayOfWeekWednesday                     -0.1706     0.7817  -0.218 0.827270    
## shiftB                                  2.5005     0.5063   4.939 7.86e-07 ***
## shiftC                                 -0.6240     0.5058  -1.234 0.217346    
## Month02                                -5.6342     1.0059  -5.601 2.13e-08 ***
## Month03                                -7.6323     0.9891  -7.717 1.20e-14 ***
## Month04                                -6.3495     0.9981  -6.361 2.00e-10 ***
## Month05                                -7.5836     0.9854  -7.696 1.41e-14 ***
## Month06                                -7.5963     1.0216  -7.436 1.05e-13 ***
## Month07                                -8.5329     0.9951  -8.575  &lt; 2e-16 ***
## Month08                                -7.2737     0.9915  -7.336 2.21e-13 ***
## Month09                                -7.4497     0.9959  -7.481 7.44e-14 ***
## Month10                                -5.7232     0.9860  -5.805 6.46e-09 ***
## Month11                                -5.1842     0.9944  -5.214 1.86e-07 ***
## Month12                                -5.2021     0.9749  -5.336 9.52e-08 ***
## AlarmTime12-17                        -49.9845     0.6514 -76.738  &lt; 2e-16 ***
## AlarmTime18-23                        -40.1459     0.6528 -61.502  &lt; 2e-16 ***
## AlarmTime6-11                         -41.2591     0.6701 -61.572  &lt; 2e-16 ***
## NatureCode50MAJ                        -7.7294    56.8312  -0.136 0.891816    
## NatureCode50MCI1                       27.0040    85.9155   0.314 0.753287    
## NatureCode50PD                         45.0858    44.2582   1.019 0.308347    
## NatureCode50PI                         11.7468    43.1613   0.272 0.785498    
## NatureCode50PIN                         6.9150    50.3770   0.137 0.890822    
## NatureCode50VOT                        43.8551    67.9249   0.646 0.518513    
## NatureCodeABDOM                        26.3874    42.9878   0.614 0.539326    
## NatureCodeACHRPD                       60.0472    46.2310   1.299 0.193998    
## NatureCodeACHRPI                       49.6325    46.2311   1.074 0.283015    
## NatureCodeALLERG                       23.6859    43.0192   0.551 0.581917    
## NatureCodeANBITE                       11.7936    43.4519   0.271 0.786071    
## NatureCodeASSLT                        22.2219    43.0910   0.516 0.606066    
## NatureCodeBCKPN                        34.2506    43.0908   0.795 0.426703    
## NatureCodeBLEED                        22.0207    42.9813   0.512 0.608419    
## NatureCodeBREATH                       20.7730    42.9697   0.483 0.628789    
## NatureCodeBRUSH                        48.3069    43.6321   1.107 0.268235    
## NatureCodeBURN                         24.7300    43.6683   0.566 0.571181    
## NatureCodeCARDIA                       11.0232    42.9896   0.256 0.797631    
## NatureCodeCHEST                        21.0846    42.9715   0.491 0.623664    
## NatureCodeCHOKE                        16.0340    43.0508   0.372 0.709562    
## NatureCodeCOALRM                      119.6694    43.0211   2.782 0.005409 ** 
## NatureCodeCODVIO                       73.9665    67.9347   1.089 0.276250    
## NatureCodeCONFIN                       29.0330    43.6706   0.665 0.506169    
## NatureCodeDIABET                       16.4890    42.9818   0.384 0.701256    
## NatureCodeDROWN                        10.8063    60.7568   0.178 0.858832    
## NatureCodeEHAZ                         46.7907    43.0476   1.087 0.277060    
## NatureCodeELEC                        -12.2493    45.5716  -0.269 0.788089    
## NatureCodeELEV                        -48.5650    48.4698  -1.002 0.316363    
## NatureCodeEXPLO                        15.8532    44.0853   0.360 0.719145    
## NatureCodeEXPOS                        14.7874    44.0274   0.336 0.736971    
## NatureCodeEXTRI                        -7.2951    46.2297  -0.158 0.874614    
## NatureCodeEYE                          28.6906    48.9859   0.586 0.558084    
## NatureCodeFALL                         31.8106    42.9782   0.740 0.459206    
## NatureCodeFALLFO                       75.4685    43.2777   1.744 0.081192 .  
## NatureCodeFIRAL                        38.2288    42.9653   0.890 0.373596    
## NatureCodeFIRAST                       46.0743    43.0613   1.070 0.284635    
## NatureCodeFIRINS                     -189.2691    85.9246  -2.203 0.027615 *  
## NatureCodeFIRINV                     -107.5676    43.9085  -2.450 0.014294 *  
## NatureCodeFSERV                        88.0140    85.9199   1.024 0.305661    
## NatureCodeFUELSP                       36.5523    43.6190   0.838 0.402038    
## NatureCodeGAS                          36.8301    43.0052   0.856 0.391773    
## NatureCodeHAR                           5.3311    50.3750   0.106 0.915719    
## NatureCodeHAZ                          41.3331    44.4666   0.930 0.352615    
## NatureCodeHAZMAT                       43.4820    43.9721   0.989 0.322736    
## NatureCodeHEAD                         22.4047    43.0229   0.521 0.602534    
## NatureCodeHEART                        21.1062    42.9918   0.491 0.623472    
## NatureCodeINACC                        26.2219    45.6769   0.574 0.565920    
## NatureCodeINVES                      -120.4648    45.8054  -2.630 0.008541 ** 
## NatureCodeLIGHT                       108.4958    45.6771   2.375 0.017537 *  
## NatureCodeMED                          16.8593    43.1383   0.391 0.695931    
## NatureCodeMEDALM                       57.5180    43.4639   1.323 0.185721    
## NatureCodeMEDEM                        14.2228    43.0287   0.331 0.740990    
## NatureCodeMEDNE                        33.8170    85.9202   0.394 0.693887    
## NatureCodeMUTUAL                      -17.8019    70.7769  -0.252 0.801411    
## NatureCodeNORESP                     -103.4574    67.9310  -1.523 0.127767    
## NatureCodeODOR                         16.5666    43.1954   0.384 0.701331    
## NatureCodeOSFIR                        29.2011    43.0088   0.679 0.497167    
## NatureCodeOVDOSE                       23.8240    42.9877   0.554 0.579439    
## NatureCodePREG                         20.6101    43.0197   0.479 0.631880    
## NatureCodePSYCH                        31.0813    43.1266   0.721 0.471096    
## NatureCodeSEIZUR                       18.4210    42.9777   0.429 0.668202    
## NatureCodeSERV                         29.4488    42.9892   0.685 0.493328    
## NatureCodeSICK                         21.5386    42.9721   0.501 0.616215    
## NatureCodeSMOKE                        31.7279    43.1991   0.734 0.462671    
## NatureCodeSTAB                         25.4310    43.0629   0.591 0.554820    
## NatureCodeSTRINJ                       -2.1027    49.6544  -0.042 0.966223    
## NatureCodeSTROKE                       20.8259    42.9779   0.485 0.627981    
## NatureCodeSTRTRP                        4.8910    45.2669   0.108 0.913958    
## NatureCodeSTRUC                        -2.0314    43.0133  -0.047 0.962332    
## NatureCodeTRAUM                        26.2160    43.1103   0.608 0.543112    
## NatureCodeTSUI                         14.0629    43.7729   0.321 0.748007    
## NatureCodeUNCON                        20.7339    42.9724   0.482 0.629456    
## NatureCodeUNKNFO                       66.8186    49.6103   1.347 0.178025    
## NatureCodeUNKNWN                       16.4417    43.0290   0.382 0.702383    
## NatureCodeVFIRE                        20.0373    44.0782   0.455 0.649409    
## NatureCodeWATER                       -86.4962    67.9272  -1.273 0.202890    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 74.4 on 130053 degrees of freedom
##   (4 observations deleted due to missingness)
## Multiple R-squared:  0.1166, Adjusted R-squared:  0.1158 
## F-statistic: 145.5 on 118 and 130053 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>From this result we are able to see in further in detail which
components affect response time and at what level due to the stepwise
regression model eliminating the components that have little to no
impact on response time.</p>
<p>After that we also tried LASSO variable selection using the glmnet
function.</p>
<pre><code>## Warning in storage.mode(xd) &lt;- &quot;double&quot;: NAs introduced by coercion</code></pre>
<pre><code>##           Length Class     Mode   
## a0          79   -none-    numeric
## beta      5214   dgCMatrix S4     
## df          79   -none-    numeric
## dim          2   -none-    numeric
## lambda      79   -none-    numeric
## dev.ratio   79   -none-    numeric
## nulldev      1   -none-    numeric
## npasses      1   -none-    numeric
## jerr         1   -none-    numeric
## offset       1   -none-    logical
## call         4   -none-    call   
## nobs         1   -none-    numeric</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<p>This result allows us to view the level of significance in terms of
each coefficient due to the shrinkage that this model produces.</p>
</div>
<div id="random-forest" class="section level3">
<h3>Random Forest</h3>
<p>As an alternative to our linear regression models we ran a tree based
random forest model. For this model we produced a bar graph to display
the significance in each variable from a model we created using the
Ranger() command. In this graph we are able to visually identify how
much the models accuracy would be affected by each variable.</p>
<p><img src="index_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>After producing the bar plot we are able to see that Nature Code
holds the most importance in relation to the model followed by Fire
District and Alarm Time.</p>
</div>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>Our extensive research has provided us with the ability to provide
sufficient results for each of our research questions. Throughout this
report, we have worked on the public data set provided by the Greensboro
Fire Department which holds all reported fire incidents in Greensboro,
NC from July 1, 2010, to May 31, 2022. Firstly, to attack our research
questions on the topics of analyzing response time and forecasting
future fire incidents we explored our data set to a great extent making
multiple univariate and bivariate visualizations. We then followed this
by using a variety of different forecasting and regression models to
produce high-accuracy results.</p>
<p>While identifying what factors affect fire service response time and
how to improve fire service response time, we first visualized the
relationship between response time and every other tested variable.
Through this, we were able to decide which variables to apply to a
linear regression model to produce the level of significance that each
variable holds with response time. In our initial linear regression
model, we tested the variables; TotalStaffonIncident, FireDistrict,
DayofWeek, shift, Month, AlarmTime, and NatureCode. We then used two
different variable selection methods (Stepwise and LASSO) and analyzed
the results between the three models. Following the results from our
linear regression models, we ran a random forest model to display the
significance that each given variable obtains. With our results from
this process, we were able to conclude that NatureCode followed by
FireDistrict and AlarmTime held the most significance in relation to
response time.</p>
<p>In regards to the effect response time has on the total loss we were
able to quickly identify this through our bivariate visualizations. In
this process, we compared the variables PropertyLoss, TotalLosses,
CivilianInjuries, CivilianFatalities, FireServiceInjuries, and
FireServiceFatalities to response time and produced scatter plots and a
combination of box and violin plots to visualize the relationship
between the two. After making our property and total loss visualizations
we were able to see a very slight relationship between them and response
time. Throughout the different distributions of response time, both
variables seemed to linger around the middle betwen 100 and 400 seconds.
Contrary to belief, it’s safe to conclude that most of the time there is
not much effect response time has on total and property loss. Given the
situation, there are definitely occasions where total and property loss
are affected massively depending on the speed at which the fire service
responds to the call. In regards to Civilian and Fire Service injuries
and fatalities, there were very few situations where either occurred
across the data set. From our visualizations, we can see that across the
twelve years there have only been ten total civilian fatalities, two
occasions where more than two civilians were reported injured, six
occasions where more than one fire service injury occurred, and
absolutely no fatalities within the fire department ever. Through our
results, we were able to conclude not much significance in the
relationship between fire service response time and total loss.</p>
<p>Furthermore, used many models to forecast the daily and monthly
frequencies of fire incidents in Greensboro, NC. The models that we used
were TBATS, ARIMA, Holt-Winters, and Combination. All the models tended
to do fairly well except when there was a drastic drop in the frequency
of fire incidents in 2020. But in general, the models followed the trend
of the plots nicely. The reason for that drop could have been covid and
when people stayed home a lot more. From our research, we found that the
models did fairly well, and sometimes some models did better than
others.</p>
</div>
<div id="discussion" class="section level2">
<h2>Discussion</h2>
<p>In this report we worked intensively in order to analyze the key
factors for reported fire incidents in Greensboro, NC using all reported
data from June 1, 2010 to May 31, 2022. When further analyzing the data
set given we were able to identify through our exploratory data analysis
as well as regression and forecasting models how each variable holds
significance in relations to fire service response time and successfully
forecast the future in regards to reported fire incidents in Greensboro,
NC. We also were able to further visualize the effects of response time
on total loss.</p>
<p>Although our extensive data set equips us with a variety of different
variables over a long time period, it is not perfect due to missing
values within the data set and human error from the importation of the
reported data. With us having to cater a bit to an imperfect data set we
were still able to produce highly accurate results with the amount of
information given. With this further exploration we were then able to
forecast an accurate prediction in terms of reported fire incidents for
the rest of the year.</p>
<p>With our research results there are now many safe assumptions that
can be made behind what holds affect within the different components
that we studied in reported fire incidents. Through our exploratory data
analysis we can see the affects of all given variables in relation to
response time. Our regression models accurately depict to what extent
the importance of each given variable has on the speed of response time.
And lastly, our forecasting model equips the Greensboro Fire Department
with an accurate prediction to continue through the rest of the year
under maximum efficiency.</p>
<p>Looking through our findings there are many different observations
that can be made in order to minimize response time thus leading towards
safer situations. We were able to identify the difference in response
time on any given day, week, year and even looked at how different
response time varies in terms of the working shift for the fire service
workers. Our findings also highlighted how much response time effects
losses in terms of civilian injuries and fatalities, fire service
injuries and fatalities, and total property loss. All of our discoveries
from this research help equip the Greensboro Fire Department with high
level information in order to perform they’re job to maximum efficiency
as well as minimizing response time in order to assure the safest
outcome possible.</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<p>1 Aleisa, E., &amp; Savsar, M. (2014). Response Time Analysis of
firefighting operations using discrete event simulation. IEEE Xplore.
Retrieved July 26, 2022, from <a
href="https://ieeexplore.ieee.org/abstract/document/7046087"
class="uri">https://ieeexplore.ieee.org/abstract/document/7046087</a></p>
<p>2 Buffington, T., &amp; Ezekoye, O. A. (2019). Statistical Analysis
of Fire Department Response Times … - researchgate. Retrieved July 26,
2022, from <a
href="https://www.researchgate.net/publication/333158843_Statistical_Analysis_of_Fire_Department_Response_Times_and_Effects_on_Fire_Outcomes_in_the_United_States"
class="uri">https://www.researchgate.net/publication/333158843_Statistical_Analysis_of_Fire_Department_Response_Times_and_Effects_on_Fire_Outcomes_in_the_United_States</a></p>
<p>3 Challands, N. (n.d.). The relationships between fire service
response time and … - researchgate. Retrieved July 26, 2022, from <a
href="https://www.researchgate.net/publication/226273683_The_Relationships_Between_Fire_Service_Response_Time_and_Fire_Outcomes"
class="uri">https://www.researchgate.net/publication/226273683_The_Relationships_Between_Fire_Service_Response_Time_and_Fire_Outcomes</a></p>
<p>4 KC, K. and Corcoran, J., 2017. Modelling residential fire incident
response times: A spatial analytic approach. Applied Geography, 84,
pp.64-74. <a href="https://doi.org/10.1016/j.apgeog.2017.03.004"
class="uri">https://doi.org/10.1016/j.apgeog.2017.03.004</a></p>
<p>5 Lian, X., Melancon, S., Presta, J.-R., Reevesman, A., Spiering, B.
J., &amp; Woodbridge, D. M.-kyung. (2019). Scalable real-time prediction
and analysis of San Francisco Fire Department Response Times. IEEE
Xplore. Retrieved July 26, 2022, from <a
href="https://ieeexplore.ieee.org/document/9060320"
class="uri">https://ieeexplore.ieee.org/document/9060320</a></p>
<p>6 Mukhopadhyay, A., Vorobeychik, Y., Dubey, A., &amp; Biswas, G.
(2017, May 1). Prioritized allocation of emergency responders based on a
continuous-time incident prediction model: Proceedings of the 16th
conference on autonomous agents and multiagent systems. ACM Other
conferences. Retrieved July 26, 2022, from <a
href="https://dl.acm.org/doi/10.5555/3091125.3091154"
class="uri">https://dl.acm.org/doi/10.5555/3091125.3091154</a></p>
<p>7 Yuanwei Li, Sikui Zhang, and Guoyi Fu. 2022. Forest fire modeling
and analysis based on K-means clustering algorithm and time series
forecasting. In 2022 2nd International Conference on Bioinformatics and
Intelligent Computing (BIC 2022), January 21–23, 2022, Harbin, China.
ACM, New York, NY, USA, 7 pages. <a
href="https://doi.org/10.1145/3523286.3524560"
class="uri">https://doi.org/10.1145/3523286.3524560</a></p>
</div>
<div id="acknowledgements" class="section level2">
<h2>Acknowledgements</h2>
<p>The authors acknowledge financial support by NSF Grant HRD#1719498
and NSA Grant #H98230-22-1-0017.</p>
</div>
<div id="appendix" class="section level2">
<h2>Appendix</h2>
<p>This section contains the code to reproduce the analysis described in
this report.</p>
<p>Below is a list of the libraries that we used throughout the
report.</p>
<div id="loading-necessary-packages" class="section level4">
<h4>Loading necessary packages</h4>
<pre class="r"><code>library(readr)
library(lubridate)
library(ggplot2)
library(dslabs)
library(dplyr)
library(ggrepel)
library(ggthemes)
library(broom)
library(glmnet)
library(MASS)
library(tidyverse)
library(Amelia)
library(mice)
library(caret)
library(forecast)
library(urca)
library(randomForest)
library(ranger)
library(astsa)</code></pre>
</div>
<div id="data-preprocessing" class="section level4">
<h4>Data Preprocessing</h4>
<pre class="r"><code>gso.fire &lt;- read_csv(&quot;Greensboro_Fire_Incidents.csv&quot;)</code></pre>
</div>
<div id="filtering-for-incidents-prior-to-june-1st-2022"
class="section level4">
<h4>Filtering for incidents prior to June 1st 2022</h4>
<pre class="r"><code>gso.fire = 
  gso.fire %&gt;%
  mutate(AlarmDate2 = make_date(Year, Month, Day)) %&gt;%
  filter(AlarmDate2 &lt; &#39;2022-06-01&#39;)</code></pre>
</div>
<div id="filter-for-property-type-1-2-family-dwellings"
class="section level4">
<h4>Filter for property type 1-2 family dwellings</h4>
<pre class="r"><code>gso.fire = gso.fire %&gt;%
  filter(PropertyUse == &#39;419 - 1 or 2 family dwelling&#39;)</code></pre>
</div>
<div id="convert-to-call-process-time-to-seconds-and-add-to-gso.fire"
class="section level4">
<h4>Convert to call process time to seconds and add to gso.fire</h4>
<pre class="r"><code>gso.fire = gso.fire %&gt;%
  mutate(call_process_period = lubridate::hms(CallProcessingTime), 
         call_process_seconds = period_to_seconds(call_process_period))</code></pre>
</div>
<div id="convert-response-time-to-seconds-and-add-to-gso.fire"
class="section level4">
<h4>Convert response time to seconds and add to gso.fire</h4>
<pre class="r"><code>gso.fire = gso.fire %&gt;%
  mutate(response_time_period = lubridate::hms(ResponseTime),
         response_time_seconds = period_to_seconds(response_time_period))</code></pre>
</div>
<div id="convert-total-response-time-to-seconds-and-add-to-gso.fire"
class="section level4">
<h4>Convert total response time to seconds and add to gso.fire</h4>
<pre class="r"><code>gso.fire = gso.fire %&gt;%
  mutate(total_response_period = lubridate::hms(TotalResponseTime),
         total_response_seconds = period_to_seconds(total_response_period))</code></pre>
</div>
<div id="cutoff-point-for-response-time" class="section level4">
<h4>Cutoff point for response time</h4>
<pre class="r"><code>cutoff.response_time = gso.fire %&gt;% 
  dplyr::select(response_time_seconds) %&gt;%
  filter(!is.na(response_time_seconds)) %&gt;%
  summarize(c = quantile(response_time_seconds, .75) + 3 * IQR(response_time_seconds)) %&gt;%
  pull(c)</code></pre>
</div>
<div id="univariate-graphs" class="section level3">
<h3>Univariate graphs</h3>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = response_time_seconds, fill = &quot;red&quot;)) +
  geom_histogram(show.legend = FALSE, color = &quot;black&quot;) +
  xlab(&quot;Response Time (Seconds)&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Distribution of Response Time&quot;) +
  theme_economist()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = TotalStaffOnIncident)) +
  geom_histogram(bins = 25,show.legend = FALSE, color = &quot;black&quot;, fill = &quot;pink&quot;) +
  scale_y_log10() +
  xlab(&quot;Total Staff on Incident&quot;) +
  ylab(&quot;Count (Log10 scale)&quot;) +
  ggtitle(&quot;Distribution of Total Staff on Incident&quot;) +
  theme_economist() +
  xlim(0,25)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  count(CivilianInjuries) %&gt;%
  mutate(nlog = log10(n)) %&gt;%
  ggplot(aes(x = CivilianInjuries, y = nlog)) +
  geom_col(color = &quot;black&quot;, fill = &quot;pink&quot;) +
  xlab(&quot;Civilian Injuries&quot;) +
  ylab(&quot;Count (Log10 scale)&quot;) +
  ggtitle(&quot;Distribution of Civilian Injuries&quot;) +
  theme_economist()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  count(CivilianFatalities) %&gt;%
  mutate(nlog = log10(n)) %&gt;%
  ggplot(aes(x = CivilianFatalities, y = nlog)) +
  geom_col(color = &quot;black&quot;, fill = &quot;pink&quot;) +
  xlab(&quot;Civilian Fatalities&quot;) +
  ylab(&quot;Count (Log10 scale)&quot;) +
  ggtitle(&quot;Distribution of Civilian Fatalities&quot;) +
  theme_economist()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  count(FireServiceInjuries) %&gt;%
  mutate(nlog = log10(n)) %&gt;%
  ggplot(aes(x = FireServiceInjuries, y = nlog)) +
  geom_col(color = &quot;black&quot;, fill = &quot;pink&quot;) +
  xlab(&quot;Fire Service Injuries&quot;) +
  ylab(&quot;Count (Log10 scale)&quot;) +
  ggtitle(&quot;Distribution of Fire Service Injuries&quot;) +
  theme_economist()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = PropertyLoss)) +
  geom_histogram(bins = 20,show.legend = FALSE, color = &quot;black&quot;, fill = &quot;pink&quot;) +
  scale_x_log10() +
  xlab(&quot;Property Loss (Log10 scale)&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Distribution of Property Loss&quot;) +
  theme_economist() </code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = TotalLosses)) +
  geom_histogram(bins = 20,show.legend = FALSE, color = &quot;black&quot;, fill = &quot;pink&quot;) +
  scale_x_log10() +
  xlab(&quot;Total Loss (Log10 scale)&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Distribution of Total Loss&quot;) +
  theme_economist() </code></pre>
<pre class="r"><code>gso.fire %&gt;%
  ggplot(aes(x = AlarmHour)) +
  geom_bar(color = &quot;black&quot;, fill = &quot;pink&quot;) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  theme(axis.text.x = element_text(angle = 45)) +
  xlab(&quot;Alarm Hour&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Frequency of Fire Alarms by Alarm Hour&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  count(station) %&gt;%
  mutate(station = reorder(station, n)) %&gt;%
  ggplot(aes(x = station, y = n)) +
  geom_bar(stat = &quot;identity&quot;, color = &quot;black&quot;, fill = &quot;pink&quot;) +
  theme(axis.text.y = element_text(size = 6)) +
  xlab(&quot;Fire Station (Station Number)&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Frequency of Calls by Fire Station&quot;) +
  coord_flip()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  count(FireDistrict) %&gt;%
  mutate(FireDistrict = reorder(FireDistrict, n)) %&gt;%
  ggplot(aes(x = FireDistrict, y = n)) +
  geom_bar(stat = &quot;identity&quot;, color = &quot;black&quot;, fill = &quot;pink&quot;) +
  theme(axis.text.y = element_text(size = 6)) +
  xlab(&quot;Fire Station (Station Number)&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Frequency of Calls by Fire District&quot;) +
  coord_flip()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  count(Year) %&gt;%
  ggplot(aes(x = Year, y = n)) +
  geom_bar(stat = &quot;identity&quot;, fill = &quot;pink&quot;, color = &quot;black&quot;) +
  scale_x_continuous(breaks = seq(2010,2022,1)) +
  xlab(&quot;Year&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Frequency of Calls by Year&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  ggplot(aes(x = shift)) +
  geom_bar(show.legend = FALSE, fill = &quot;pink&quot;, color = &quot;black&quot;) +
  xlab(&quot;Shift&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Frequency of Calls by Shift&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  ggplot(aes(x = DayOfWeek)) +
  geom_bar(fill = &quot;pink&quot;, color = &quot;black&quot;) +
  xlab(&quot;Days of the Week&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Frequency of Calls by Days of the Week&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  ggplot(aes(x = Week)) +
  geom_bar(fill = &quot;pink&quot;, color = &quot;black&quot;) +
  scale_x_continuous(breaks = seq(1,53,1)) +
  theme(axis.text.x = element_text(angle = 90)) +
  xlab(&quot;Week&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Frequency of Calls by Week&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  ggplot(aes(x = Month)) +
  geom_bar(fill = &quot;pink&quot;, color = &quot;black&quot;) +
  xlab(&quot;Month&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Frequency of Calls by Month&quot;)</code></pre>
</div>
<div id="bivariate-graphs" class="section level3">
<h3>Bivariate Graphs</h3>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = Week, y = response_time_seconds, group = Week)) +
  geom_boxplot() +
  scale_x_continuous(breaks = seq(1,53,1)) +
  theme(axis.text.x = element_text(angle = 90)) +
  xlab(&quot;Week&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Week vs Response Time&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = station, y = response_time_seconds)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) +
  xlab(&quot;Station&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Station vs Response Time&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = AlarmHour, y = response_time_seconds, group = AlarmHour)) +
  geom_boxplot() +
  scale_x_continuous(breaks = seq(0,23,1)) +
  xlab(&quot;Alarm Hour&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Alarm Hour vs Response Time&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = NumberOfAlarms, y = response_time_seconds, group = NumberOfAlarms)) +
  geom_boxplot(show.legend = FALSE) +
  xlab(&quot;Number of Alarms&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Number of Alarms vs Response Time&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = NatureCode, y = response_time_seconds)) +
  theme(axis.text.x = element_text(angle = 90)) +
  geom_boxplot() +
  xlab(&quot;Nature Code&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Nature Code vs Response Time&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(y = TotalLosses, x = as.factor(AlarmHour))) +
  geom_boxplot(show.legend = FALSE) +
  scale_y_log10() +
  ylab(&quot;Total Loss (Log10 scale)&quot;) +
  xlab(&quot;Alarm Hour&quot;) +
  ggtitle(&quot;Total Loss by Alarm Hour&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(y = TotalLosses, x = shift)) +
  geom_boxplot(show.legend = FALSE) +
  scale_y_log10() +
  ylab(&quot;Total Loss (Log10 scale)&quot;) +
  xlab(&quot;Shift&quot;) +
  ggtitle(&quot;Total Loss by Shift&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(y = PropertyLoss, x = as.factor(AlarmHour))) +
  geom_boxplot(show.legend = FALSE) +
  scale_y_log10() +
  ylab(&quot;Property Loss (Log10 scale)&quot;) +
  xlab(&quot;Alarm Hour&quot;) +
  ggtitle(&quot;Property Loss by Alarm Hour&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(y = PropertyLoss, x = shift)) +
  geom_boxplot(show.legend = FALSE) +
  scale_y_log10() +
  ylab(&quot;Property Loss (Log10 scale)&quot;) +
  xlab(&quot;Shift&quot;) +
  ggtitle(&quot;Property Loss by Shift&quot;) +
  theme_economist()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = response_time_seconds, y = CivilianInjuries)) +
  geom_point(stat = &quot;identity&quot;, show.legend = FALSE) +
  ylab(&quot;Civilian Injuries&quot;) +
  xlab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Civilian Injuries vs Response Time&quot;) +
  theme_economist() </code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = TotalStaffOnIncident, y = response_time_seconds)) +
  geom_point(stat = &quot;identity&quot;, show.legend = FALSE) +
  xlab(&quot;Total Staff On Incident&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Total Staff on Incident vs Response Time&quot;) +
  theme_economist()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(y = PropertyLoss, x = response_time_seconds)) +
  geom_point(stat = &quot;identity&quot;, show.legend = FALSE) +
  scale_y_log10() +
  ylab(&quot;Property Loss (Log10 scale)&quot;) +
  xlab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Property Loss vs Response Time&quot;) +
  theme_economist()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(y = TotalLosses, x = response_time_seconds)) +
  geom_point(stat = &quot;identity&quot;, show.legend = FALSE) +
  scale_y_log10() +
  ylab(&quot;Total Loss (Log10 scale)&quot;) +
  xlab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Total Loss vs Response Time&quot;) +
  theme_economist()</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(!is.na(response_time_seconds)) %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = DayOfWeek, y = response_time_seconds)) +
  geom_violin(trim = FALSE, fill = &quot;light blue&quot;) +
  geom_boxplot(width = 0.3, fill = &quot;pink&quot;) +
  xlab(&quot;Days of the Week&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin &amp; Box Plot of Response Time Densities by Days of the Week&quot;) +
  theme(axis.text.x = element_text(angle = 90), legend.position = &quot;hide&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = Year, y = response_time_seconds, group = Year)) +
  geom_violin(trim = FALSE, fill = &quot;light blue&quot;) +
  geom_boxplot(show.legend = FALSE, width = .3, fill = &quot;pink&quot;) +
  scale_x_continuous(breaks = seq(2010,2022,1)) +
  xlab(&quot;Year&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin &amp; Box Plot of Response Time Densities by Year&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = shift, y = response_time_seconds)) +
  geom_violin(show.legend = FALSE, fill = &quot;light blue&quot;) +
  geom_boxplot(width = .5, show.legend = FALSE, fill = &quot;pink&quot;) +
  xlab(&quot;Work shift&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin and Box Plot of Response Time Densities by Work Shift&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = FireDistrict, y = response_time_seconds)) +
  geom_violin(fill = &quot;light blue&quot;) +
  geom_boxplot(show.legend = FALSE, width = .2, fill = &quot;pink&quot;) +
  theme(axis.text.x = element_text(angle = 90), legend.position = &quot;hide&quot;) +
  xlab(&quot;Fire District&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin and Box Plot of Response Time Densities by Fire District&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = Month, y = response_time_seconds)) +
  geom_violin(show.legend = FALSE, fill = &quot;light blue&quot;) +
  geom_boxplot(show.legend = FALSE, width = .3, fill = &quot;pink&quot;) +
  xlab(&quot;Month&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin and Box Plot of Response Time Densities by Month&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = AlarmHour, y = response_time_seconds, group = AlarmHour)) +
  geom_violin(fill = &quot;light blue&quot;) +
  geom_boxplot(width = .3, fill = &quot;pink&quot;) +
  scale_x_continuous(breaks = seq(0,23,1)) +
  xlab(&quot;Alarm Hour&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin and Box Plot of Response Time Densities by Alarm Hour&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = NumberOfAlarms, y = response_time_seconds, group = NumberOfAlarms)) +
  geom_violin(fill = &quot;light blue&quot;) +
  geom_boxplot(width = .3, fill = &quot;pink&quot;) +
  xlab(&quot;Number of Alarms&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin and Box Plot of Response Time Densities by Number of Alarms&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = CivilianInjuries, y = response_time_seconds, group = CivilianInjuries)) +
  geom_violin(show.legend = FALSE, fill = &quot;light blue&quot;) +
  geom_boxplot(width = .5, show.legend = FALSE, fill = &quot;pink&quot;) +
  xlab(&quot;Civilian Injuries&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin and Box Plot of Response Time Densities by Civilian Injuries&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = CivilianFatalities, y = response_time_seconds, group = CivilianFatalities)) +
  geom_violin(show.legend = FALSE, fill = &quot;light blue&quot;) +
  geom_boxplot(width = .5, show.legend = FALSE, fill = &quot;pink&quot;) +
  xlab(&quot;Civilian Fatalities&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin and Box Plot of Response Time Densities by Civilian Fatalities&quot;)</code></pre>
<pre class="r"><code>gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;%
  ggplot(aes(x = FireServiceInjuries, y = response_time_seconds, group = FireServiceInjuries)) +
  geom_violin(show.legend = FALSE, fill = &quot;light blue&quot;) +
  geom_boxplot(width = .5, show.legend = FALSE, fill = &quot;pink&quot;) +
  xlab(&quot;Fire Service Injuries&quot;) +
  ylab(&quot;Response Time (Seconds)&quot;) +
  ggtitle(&quot;Violin and Box Plot of Response Time Densities by Fire Service Injuries&quot;)</code></pre>
</div>
<div id="time-series-visualization-1" class="section level3">
<h3>Time Series Visualization</h3>
<p>Visualization of fire incidents in Greensboro, NC from July 1, 2010
to May 31, 2022.</p>
<pre class="r"><code>gso.fire.ts = gso.fire %&gt;%
  count(AlarmDate2)</code></pre>
<pre class="r"><code>gso.fire.ts %&gt;%
  ggplot(aes(x = AlarmDate2, y = n)) +
  geom_line() +
  scale_x_date(date_labels = &quot;%m-%Y&quot;, date_breaks = &quot;6 month&quot;) + 
  xlab(&quot;Year&quot;) +
  ylab(&quot;Number of Fire Incidents&quot;) +
  ggtitle(&quot;Time series of daily number of fire incidents&quot;) +
  theme(axis.text.x = element_text(angle = 90))</code></pre>
<pre class="r"><code>incidents_annual = gso.fire.ts %&gt;%
  separate(AlarmDate2, sep=&quot;-&quot;, into = c(&quot;Year&quot;, &quot;Month&quot;, &quot;Day&quot;))

incidents_annual = cbind(incidents_annual, gso.fire.ts$AlarmDate2)
colnames(incidents_annual) = c(&quot;Year&quot;,&quot;Month&quot;,&quot;Day&quot;,&quot;n&quot;,&quot;AlarmDate2&quot;)

incidents_annual %&gt;%
  ggplot(aes(x = AlarmDate2, y = n)) + 
  ggtitle(&quot;Time Series Plots for Frequency of Daily Fire Incidents Organized by Year&quot;) + 
  geom_line() + 
  scale_x_date(date_labels = &quot;%m-%Y&quot;, date_breaks = &quot;1 month&quot;) + 
  xlab(&quot;Date&quot;) + ylab(&quot;Count&quot;) + 
  theme(axis.text.x = element_text(angle = 90, size = 14)) +
  theme(axis.text.y = element_text(size = 14)) +
  theme(plot.title = element_text(size=22)) +
  theme(axis.title=element_text(size=18)) +
  facet_wrap(~Year, scales = &quot;free_x&quot;)</code></pre>
<p>Monthly time series visualizations</p>
<pre class="r"><code>gso.fire.ts.month = gso.fire %&gt;%
  mutate(Monthly = make_date(Year, Month)) %&gt;%
  group_by(Monthly, Month, Year) %&gt;%
  count()</code></pre>
<pre class="r"><code>gso.fire.ts.month %&gt;%
  ggplot(aes(x = Monthly, y = n)) +
  geom_line() +
  scale_x_date(date_labels = &quot;%m-%y&quot;, date_breaks = &quot;6 month&quot;) + 
  xlab(&quot;Month&quot;) +
  ylab(&quot;Number of Fire Incidents&quot;) +
  ggtitle(&quot;Time series of monthly number of fire incidents for 2010-2022&quot;) +
  theme(axis.text.x = element_text(angle = 90))</code></pre>
</div>
<div id="time-series-forecasting-1" class="section level3">
<h3>Time Series Forecasting</h3>
<pre class="r"><code>#forecasting for daily number of fire incidents
gso.fire.ts.2 = ts(gso.fire.ts$n, start = c(2010, 182), end = c(2022, 153),
                 frequency = 365)
ndiffs(gso.fire.ts.2)
ndiffs(gso.fire.ts.2)
acf(gso.fire.ts.2)
summary(ur.kpss(gso.fire.ts.2))

#attempt at differencing
gso.fire.ts.2.dif = diff(gso.fire.ts.2)
acf(gso.fire.ts.2.dif)

cbind(&quot;Fire Incidents&quot; = gso.fire.ts.2,
      &quot;First differenced&quot; = diff(gso.fire.ts.2)) %&gt;%
  autoplot(facets=TRUE) +
  xlab(&quot;Date&quot;) + ylab(&quot;&quot;) +
  ggtitle(&quot;Stationarity Transformations of Daily Fire Incidents&quot;)

y.dif = msts(gso.fire.ts.2.dif, seasonal.periods=c(7,365.25))
daily.dif.tbats = tbats(y.dif)
daily.dif.tbats.fc = forecast::forecast(daily.dif.tbats, h = 214)

#point forecast values
dif.Yhat = daily.dif.tbats.fc$mean
dif.Yhat.upper = daily.dif.tbats.fc$upper
dif.Yhat.lower = daily.dif.tbats.fc$lower

Yhat = cumsum(c(gso.fire.ts.2[length(gso.fire.ts.2)],dif.Yhat))
Yhat = ts(Yhat, start = c(2022, 152), frequency=365)
Yhat_upper = cumsum(c(gso.fire.ts.2[length(gso.fire.ts.2)],dif.Yhat.upper))
Yhat_upper = ts(Yhat_upper, start = c(2022, 152), end = c(2023,1), frequency=365)
Yhat_lower = cumsum(c(gso.fire.ts.2[length(gso.fire.ts.2)],dif.Yhat.lower))
Yhat_lower = ts(Yhat_lower, start = c(2022, 152), end = c(2023,1), frequency=365)

fire.ts = ts(gso.fire.ts.2[3992:4352],start = c(2021, 25), end = c(2022, 153),
              frequency = 360) # A 360 day trim to see forecast better

#TBAT forecasting
autoplot(fire.ts) + 
  autolayer(Yhat, series=&quot;Point Forecasts&quot;) + 
  ggtitle(&quot;TBATS Forecasting Model for Daily Number of Fire Incidents&quot;) +
  xlab(&quot;Date&quot;) + ylab(&quot;Fire Incidents&quot;) + 
  theme(title = element_text(size = 10), legend.position = &quot;bottom&quot;)

accuracy(daily.dif.tbats.3)</code></pre>
<pre class="r"><code>#ARIMA forecasting
daily.arima = auto.arima(gso.fire.ts.2)
daily.arima.fc = forecast(daily.arima, h=214)
autoplot(daily.arima.fc) +
  ggtitle(&quot;ARIMA Forecasting Model for Daily Number of Fire Incidents&quot;) +
  xlab(&quot;Date&quot;) + 
  coord_cartesian(xlim = c(2020, 2023)) +
  ylab(&quot;Fire Incidents&quot;) + 
  theme(title = element_text(size = 10))

accuracy(daily.arima.3)</code></pre>
<pre class="r"><code>gso.fire.ts.3 = ts(gso.fire.ts$n, start = c(2010, 182), end = c(2022, 59),
                                 frequency = 365)
#attempt at differencing
gso.fire.ts.3.dif = diff(gso.fire.ts.3)

y.dif.3 = msts(gso.fire.ts.3.dif, seasonal.periods=c(7,365.25))
daily.dif.tbats.3 = tbats(y.dif.3)
daily.dif.tbats.fc.3 = forecast::forecast(daily.dif.tbats.3, h=671)
dif.Yhat.3 = daily.dif.tbats.fc.3$mean #point forecast values 

Yhat.3 = cumsum(c(gso.fire.ts.3[length(gso.fire.ts.3)],dif.Yhat.3))
Yhat.3 = ts(Yhat.3, start = c(2022, 60), frequency=365)

gso.fire.ts.true = ts(gso.fire.ts$n, start = c(2010, 182), end = c(2022, 153),
                    frequency = 365)
#TBAT forecasting
autoplot(gso.fire.ts.3) + 
  autolayer(gso.fire.ts.true, alpha=0.7, series=&quot;True Count&quot;) +
  autolayer(Yhat.3, alpha=0.6, series=&quot;Point Forecasts&quot;) + 
  ggtitle(&quot;TBATS Forecasting Model for Daily Number of Fire Incidents&quot;) +
  xlab(&quot;Date&quot;) +
  ylab(&quot;Fire Incidents&quot;) + 
  theme(title = element_text(size = 10), legend.position = &quot;bottom&quot;)

accuracy(daily.dif.tbats.3)</code></pre>
<pre class="r"><code>#ARIMA forecasting
daily.arima.3 = auto.arima(gso.fire.ts.3)
daily.arima.fc.3 = forecast(daily.arima.3, h=671)
autoplot(daily.arima.fc.3) + 
  ggtitle(&quot;ARIMA Forecasting Model for Daily Number of Fire Incidents&quot;) +
  xlab(&quot;Date&quot;) +
  coord_cartesian(xlim = c(2020, 2023)) +
  ylab(&quot;Fire Incidents&quot;) + 
  theme(title = element_text(size = 10))

accuracy(daily.arima.3)</code></pre>
<p>Forecasting for monthly number of fire incidents.</p>
<pre class="r"><code>#convert gso.fire.ts.month to official ts object
gso.fire.ts.month.2 = ts(gso.fire.ts.month$n, start = c(2010, 07, 01), end = c(2022, 05, 01),
                          frequency = 12)

#looking at stationarity
acf(gso.fire.ts.month.2)
summary(ur.kpss(gso.fire.ts.month.2))

ndiffs(gso.fire.ts.month.2) #1
nsdiffs(gso.fire.ts.month.2) #0

#attempt at differencing
gso.fire.ts.month.2.dif = diff(gso.fire.ts.month.2)

#looking at stationarity for difference
acf(gso.fire.ts.month.2.dif)

summary(ur.kpss(gso.fire.ts.month.2.dif))
ndiffs(gso.fire.ts.month.2.dif) #0
nsdiffs(gso.fire.ts.month.2.dif) #0

cbind(&quot;Fire Incidents&quot; = gso.fire.ts.month.2,
      &quot;First differenced&quot; = diff(gso.fire.ts.month.2)) %&gt;%
  autoplot(facets=TRUE) +
  xlab(&quot;Date&quot;) + ylab(&quot;&quot;) +
  ggtitle(&quot;Stationarity Transformation of Monthly Fire Incidents&quot;)</code></pre>
<pre class="r"><code>y.dif.month = msts(gso.fire.ts.month.2.dif, seasonal.periods=12)
dif.tbats.month = tbats(y.dif.month)
dif.tbats.month.fc = forecast::forecast(dif.tbats.month, h = 8)

#point forecast values
dif.Yhat.month = dif.tbats.month.fc$mean

Yhat.month = cumsum(c(gso.fire.ts.month.2[length(gso.fire.ts.month.2)],dif.Yhat.month))
Yhat.month = ts(Yhat.month, start = c(2022, 05), frequency=12)

#TBATS forecasting
autoplot(gso.fire.ts.month.2) + 
  autolayer(Yhat.month, series=&quot;Point Forecasts&quot;) + 
  ggtitle(&quot;TBATS Forecasting Model for Monthly Frequency of Fire Incidents&quot;) +
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) + 
  theme(axis.text.x = element_text(angle = 90), title = element_text(size=10), 
        legend.position = &quot;bottom&quot;) 

#checking accuracy
accuracy(dif.tbats.month)</code></pre>
<pre class="r"><code>#ARIMA forecasting
monthly.arima = auto.arima(gso.fire.ts.month.2)
monthly.arima.fc = forecast(monthly.arima, h=8)
autoplot(monthly.arima.fc) +
  ggtitle(&quot;ARIMA Forecasting Model for Monthly Frequency of Fire Incidents&quot;) +
  xlab(&quot;Date&quot;) + 
  coord_cartesian(xlim = c(2020, 2023)) +
  ylab(&quot;Frequency of Fire Incidents&quot;) + 
  theme(title = element_text(size = 10))

#checking accuracy
accuracy(monthly.arima)</code></pre>
<pre class="r"><code>#HoltWinters forecasting
dif.monthly.holt = HoltWinters(gso.fire.ts.month.2.dif)
dif.fcast.monthly = forecast::forecast(dif.monthly.holt, h=8, level=c(80,95))
dYhat.Holt = dif.fcast.monthly$mean

Yhat.Holt = cumsum(c(gso.fire.ts.month.2[length(gso.fire.ts.month.2)],dYhat.Holt))
Yhat.Holt = ts(Yhat.Holt, start = c(2022, 05), frequency=12)

autoplot(gso.fire.ts.month.2) +
  autolayer(Yhat.Holt, series = &quot;Point Forecasts&quot;) +
  ggtitle(&quot;Forecasts for Monthly Frequency of Fire Incidents using HoltWinters&quot;) +
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) +
  theme(axis.text.x = element_text(angle = 90), title = element_text(size=9), 
        legend.position = &quot;bottom&quot;)

#checking accuracy
accuracy(dif.fcast.monthly)</code></pre>
<p>Multi-step forecasting for daily data</p>
<pre class="r"><code>#getting differenced training and test sets 
y.dif.2 = msts(gso.fire.ts.2.dif, seasonal.periods=c(7,365.25))
dif.training.tbats.2 = subset(y.dif.2, end=length(y.dif.2)-151)
dif.test.tbats.2 = subset(y.dif.2, start=length(y.dif.2)-150)
dif.daily.train.tbats.2 = tbats(dif.training.tbats.2)
dif.train.fc = forecast(dif.daily.train.tbats.2, h=151)

#getting point forecasts 
dYhat.tbats = dif.train.fc$mean

#setting up normal ts training and test sets 
y.2 = msts(gso.fire.ts.2, seasonal.periods=c(7,365.25))
training.tbats.2 = subset(y.2, end=length(y.2)-151)
test.tbats.2 = subset(y.2, start=length(y.2)-150)

#reverting back to original points   
Yhat.tbats = cumsum(c(training.tbats.2[length(training.tbats.2)], dYhat.tbats))
Yhat.tbats = ts(Yhat.tbats, start = c(2022, 1), frequency = 365)

autoplot(training.tbats.2) + 
  autolayer(Yhat.tbats, series=&quot;Point Forecasts&quot;) + 
  autolayer(test.tbats.2, series=&quot;Test Set&quot;, alpha = 0.7) + 
  ggtitle(&quot;Multi-Step TBATS Daily Forecasts of Frequency of Fire Incidents&quot;) + 
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) +
  coord_cartesian(xlim = c(2020, 2023)) +
  theme(legend.position = &quot;bottom&quot;)

dif.daily.test.tbats.2 = tbats(dif.test.tbats.2)
accuracy(dif.daily.test.tbats.2)</code></pre>
<pre class="r"><code>#multi-step ARIMA forecast for daily data
training.arima = subset(gso.fire.ts.2, end=length(gso.fire.ts.2)-151)
test.arima = subset(gso.fire.ts.2, start=length(gso.fire.ts.2)-150)
daily.train.arima = auto.arima(training.arima)
fc.train.arima = forecast(daily.train.arima, h=151)

autoplot(fc.train.arima) + 
  autolayer(test.arima, series=&quot;Test Set&quot;, alpha = 0.7) + 
  ggtitle(&quot;Multi-Step ARIMA Daily Forecasts of Frequency of Fire Incidents&quot;) + 
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) + 
  coord_cartesian(xlim = c(2020, 2023)) +
  theme(legend.position = &quot;bottom&quot;)

daily.test.arima = arima(test.arima)
accuracy(daily.test.arima)</code></pre>
<pre class="r"><code>#time series combination
train = window(gso.fire.ts.2, end=c(2019, 12))
h = length(gso.fire.ts.2) - length(train)

#ARIMA model 
ARIMA = forecast::forecast(auto.arima(train, lambda=0, biasadj=TRUE), h=h)

#TBATS model 
train.tbats = msts(gso.fire.ts.2.dif, end=c(2019,12), seasonal.periods = c(7,365.25))
TBATS = forecast::forecast(tbats(train.tbats, biasadj = TRUE), h=h)
dYhat.combo = TBATS$mean

Yhat.combo = cumsum(c(train[length(train)], dYhat.combo))
Yhat.combo = ts(Yhat.combo, start = c(2019, 12), frequency = 365)
Combination = (ARIMA[[&quot;mean&quot;]] + Yhat.combo)/2
true.daily = gso.fire.ts %&gt;%
  filter(AlarmDate2 &gt;= as.Date(&quot;2019/12/01&quot;) &amp; AlarmDate2 &lt;= as.Date(&quot;2021/05/31&quot;))
true.daily.ts = ts(true.daily$n, 
                            start = c(2019,12), end = c(2021,153), 
                            frequency = 365)

autoplot(train) +
  autolayer(true.daily.ts) +
  autolayer(Combination, series=&quot;Combination&quot;, alpha=0.8) +
  autolayer(ARIMA, series=&quot;ARIMA&quot;, PI=F) +
  autolayer(Yhat.combo, series=&quot;TBATS&quot;, alpha=0.7) +
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) +
  ggtitle(&quot;Time Series Combination for Daily Frequency of Fire Incidents&quot;) + 
  theme(legend.position = &quot;bottom&quot;)

c(ARIMA = accuracy(ARIMA, gso.fire.ts.2)[&quot;Test set&quot;, &quot;RMSE&quot;],
  TBATS = accuracy(Yhat.combo, gso.fire.ts.2)[&quot;Test set&quot;, &quot;RMSE&quot;],
  Combination =
    accuracy(Combination, gso.fire.ts.2)[&quot;Test set&quot;, &quot;RMSE&quot;])</code></pre>
<p>Multi-step forecasting for monthly data</p>
<pre class="r"><code>#multi-step TBATS
y2.dif.monthly = msts(gso.fire.ts.month.2.dif, seasonal.periods=12)
dif.training.tbats.2.monthly = subset(y2.dif.monthly, end=length(y2.dif.monthly)-5)
dif.test.tbats.2.monthly = subset(y2.dif.monthly, start=length(y2.dif.monthly)-4)
dif.train.tbats.2.monthly = tbats(dif.training.tbats.2.monthly)
dif.fc.train.tbats.2.monthly = forecast(dif.train.tbats.2.monthly, h=5)
dYhat.ms.tbats.monthly = dif.fc.train.tbats.2.monthly$mean

y2.monthly = msts(gso.fire.ts.month.2, seasonal.periods=12)
training.tbats.monthly.2 = subset(y2.monthly, end=length(y2.monthly)-5)
test.tbats.monthly.2 = subset(y2.monthly, start=length(y2.monthly)-4)

Yhat.ms.tbats.monthly = cumsum(c(training.tbats.monthly.2[length(training.tbats.monthly.2)],
                                 dYhat.ms.tbats.monthly))
Yhat.ms.tbats.monthly = ts(Yhat.ms.tbats.monthly, start = c(2022,01), frequency=12)

autoplot(training.tbats.monthly.2) + 
  autolayer(Yhat.ms.tbats.monthly, series=&quot;Point Forecasts&quot;) + 
  autolayer(test.tbats.monthly.2, series=&quot;Test Set&quot;, alpha = 0.7) + 
  ggtitle(&quot;Multi-Step TBATS Monthly Forecasts of Frequency of Fire Incidents&quot;) + 
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) + 
  theme(legend.position = &quot;bottom&quot;, title=element_text(size=10)) + 
  theme(axis.text.x = element_text(angle = 90))

dif.test.tbats.2.monthly = tbats(dif.test.tbats.2.monthly)
accuracy(dif.test.tbats.2.monthly)</code></pre>
<pre class="r"><code>#multi-step ARIMA
training.arima.monthly = subset(gso.fire.ts.month.2, end=length(gso.fire.ts.month.2)-5)
test.arima.monthly = subset(gso.fire.ts.month.2, start=length(gso.fire.ts.month.2)-4)
train.arima.monthly.3 = auto.arima(training.arima.monthly)
fc.train.arima.monthly = forecast(train.arima.monthly.3, h=5)

autoplot(fc.train.arima.monthly) + 
  autolayer(test.arima.monthly, series=&quot;Test Set&quot;, alpha = 0.7) + 
  ggtitle(&quot;Multi-Step ARIMA Monthly Forecasts of Frequency of Fire Incidents&quot;) + 
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) + 
  coord_cartesian(xlim = c(2018, 2023)) +
  theme(legend.position = &quot;bottom&quot;) + 
  theme(axis.text.x = element_text(angle = 90), title = element_text(size=9), 
        legend.position = &quot;bottom&quot;)

test.arima.monthly.3 = arima(test.arima.monthly)
accuracy(test.arima.monthly.3)</code></pre>
<pre class="r"><code>#multi-step HoltWinters
dif.training.HW.monthly = subset(gso.fire.ts.month.2.dif, end=length(gso.fire.ts.month.2.dif)-5)
dif.test.HW.monthly = subset(gso.fire.ts.month.2.dif, start=length(gso.fire.ts.month.2.dif)-4)
dif.train.HW.monthly = HoltWinters(dif.training.HW.monthly)
dif.fc.HW = forecast::forecast(dif.train.HW.monthly, h=5)

dYhat.ms.HW = dif.fc.HW$mean
Yhat.ms.HW = cumsum(c(gso.fire.ts.month.2[length(gso.fire.ts.month.2)],dYhat.ms.HW))
Yhat.ms.HW = ts(Yhat.ms.HW, start = c(2022,01,01), frequency=12)

training.HW.monthly = subset(gso.fire.ts.month.2, end=length(gso.fire.ts.month.2)-5)
test.HW.monthly = subset(gso.fire.ts.month.2, start=length(gso.fire.ts.month.2)-4)
true.count.monthly = ts(gso.fire.ts.month.2, start=c(2010,07,01), end=c(2021,12,31), frequency=12)

autoplot(training.HW.monthly) + 
  autolayer(Yhat.ms.HW, series = &quot;Point Forecasts&quot;) + 
  autolayer(test.HW.monthly, series = &quot;Test Set&quot;) + 
  ggtitle(&quot;Multi-Step HoltWinters Monthly Forecasts of Frequency of Fire Incidents&quot;) + 
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) +
  theme(axis.text.x = element_text(angle = 90), legend.position = &quot;bottom&quot;, 
        title = element_text(size = 9))

accuracy(Yhat.ms.HW, gso.fire.ts.month.2)</code></pre>
<pre class="r"><code>#multi-step HoltWinters
dif.training.HW.monthly = subset(gso.fire.ts.month.2.dif, end=length(gso.fire.ts.month.2.dif)-5)
dif.test.HW.monthly = subset(gso.fire.ts.month.2.dif, start=length(gso.fire.ts.month.2.dif)-4)
dif.train.HW.monthly = HoltWinters(dif.training.HW.monthly)
dif.fc.HW = forecast::forecast(dif.train.HW.monthly, h=5)

dYhat.ms.HW = dif.fc.HW$mean
Yhat.ms.HW = cumsum(c(gso.fire.ts.month.2[length(gso.fire.ts.month.2)],dYhat.ms.HW))
Yhat.ms.HW = ts(Yhat.ms.HW, start = c(2022,01,01), frequency=12)

training.HW.monthly = subset(gso.fire.ts.month.2, end=length(gso.fire.ts.month.2)-5)
test.HW.monthly = subset(gso.fire.ts.month.2, start=length(gso.fire.ts.month.2)-4)
true.count.monthly = ts(gso.fire.ts.month.2, start=c(2010,07,01), end=c(2021,12,31), frequency=12)

autoplot(training.HW.monthly) + 
  autolayer(Yhat.ms.HW, series = &quot;Point Forecasts&quot;) + 
  autolayer(test.HW.monthly, series = &quot;Test Set&quot;) + 
  ggtitle(&quot;Multi-Step HoltWinters Monthly Forecasts of Frequency of Fire Incidents&quot;) + 
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) +
  theme(axis.text.x = element_text(angle = 90), legend.position = &quot;bottom&quot;, 
        title = element_text(size = 9))

accuracy(Yhat.ms.HW, gso.fire.ts.month.2)</code></pre>
<pre class="r"><code>#Time series combination for monthly
train.monthly.2 = window(gso.fire.ts.month.2, end=c(2021, 05))
h.monthly.2 = length(gso.fire.ts.month.2) - length(train.monthly.2)

#ARIMA model 
ARIMA.monthly.2 = forecast::forecast(auto.arima(train.monthly.2, lambda=0, biasadj=TRUE),
                                   h=h.monthly.2)

#TBATS model 
train.tbats.monthly.2 = msts(gso.fire.ts.month.2.dif, end=c(2021,05), seasonal.periods = 12)
tbats.monthly.2 = forecast::forecast(tbats(train.tbats.monthly.2, biasadj = TRUE),
                                     h=h.monthly.2)
dYhat.combo.monthly.2 = tbats.monthly.2$mean

Yhat.combo.monthly.2 = cumsum(c(train.monthly.2[length(train.monthly.2)], dYhat.combo.monthly.2))
Yhat.combo.monthly.2 = ts(Yhat.combo.monthly.2, start = c(2021,05), frequency = 12)

#HoltWinters Model 
HW.monthly.2 = forecast::forecast(HoltWinters(gso.fire.ts.month.2.dif), h=h.monthly.2)

dYhat.HW.monthly.2 = HW.monthly.2$mean

Yhat.HW.monthly.2 = cumsum(c(train.monthly.2[length(train.monthly.2)],dYhat.HW.monthly.2))
Yhat.HW.monthly.2 = ts(Yhat.HW.monthly.2, start = c(2021,05), frequency=12)
Combination.monthly.2 = (ARIMA.monthly.2[[&quot;mean&quot;]] + Yhat.combo.monthly.2 + 
                           Yhat.HW.monthly.2)/3

y.monthly = msts(gso.fire.ts.month.2, seasonal.periods=12)
test.monthly = subset(y.monthly, start=length(y.monthly)-12)

autoplot(train.monthly.2) +
  autolayer(test.monthly, series=&quot;True Count&quot;) +
  autolayer(Combination.monthly.2, series=&quot;Combination&quot;, alpha=0.8) +
  autolayer(ARIMA.monthly.2, series=&quot;ARIMA&quot;, PI=F) +
  autolayer(Yhat.combo.monthly.2, series=&quot;TBATS&quot;, alpha=0.7) +
  autolayer(Yhat.HW.monthly.2, series=&quot;HoltWinters&quot;, alpha=0.7) + 
  xlab(&quot;Date&quot;) +
  ylab(&quot;Frequency of Fire Incidents&quot;) +
  ggtitle(&quot;Time Series Combination for Monthly Frequency of Fire Incidents&quot;) + 
  theme(axis.text.x = element_text(angle = 90), legend.position = &quot;bottom&quot;, 
        title = element_text(size = 9)) 

c(ARIMA = accuracy(ARIMA.monthly.2, gso.fire.ts.month.2)[&quot;Test set&quot;, &quot;RMSE&quot;],
  TBATS = accuracy(Yhat.combo.monthly.2, gso.fire.ts.month.2)[&quot;Test set&quot;, &quot;RMSE&quot;],
  HW = accuracy(Yhat.HW.monthly.2, gso.fire.ts.month.2)[&quot;Test set&quot;, &quot;RMSE&quot;],
  Combination =
    accuracy(Combination.monthly.2, gso.fire.ts.month.2)[&quot;Test set&quot;, &quot;RMSE&quot;])</code></pre>
</div>
<div id="modeling-of-response-time-1" class="section level3">
<h3>Modeling of Response Time</h3>
<pre class="r"><code>gso.fire.filtered = gso.fire %&gt;%
  filter(response_time_seconds &lt; cutoff.response_time) %&gt;% 
  dplyr::select(response_time_seconds, everything())

gso.fire.filtered = gso.fire.filtered %&gt;%
  mutate(AlarmTime = case_when(AlarmHour &gt;= 0 &amp; AlarmHour &lt; 6 ~ &quot;0-5&quot;, 
                               AlarmHour &gt;= 6 &amp; AlarmHour &lt; 12 ~ &quot;6-11&quot;,
                               AlarmHour &gt;= 12 &amp; AlarmHour &lt; 18 ~ &quot;12-17&quot;,
                               TRUE ~ &quot;18-23&quot;))</code></pre>
</div>
<div id="linear-regression-model" class="section level3">
<h3>Linear Regression Model</h3>
<pre class="r"><code>#manual variable selection
lm.res.time = lm(response_time_seconds ~ TotalStaffOnIncident + FireDistrict + DayOfWeek + 
                   shift + Month + AlarmTime + NatureCode, data = gso.fire.filtered)
summary(lm.res.time)
round(coef(lm.res.time), 4)</code></pre>
<pre class="r"><code>lm.res.time.select = stepAIC(lm.res.time)
summary(lm.res.time.select)</code></pre>
<pre class="r"><code>#Lasso variable selection
las.Mod &lt;- glmnet(as.matrix(gso.fire.filtered[,-1]), gso.fire.filtered$response_time_seconds, family = &quot;gaussian&quot;)
plot(las.Mod)</code></pre>
</div>
<div id="random-forest-1" class="section level3">
<h3>Random Forest</h3>
<pre class="r"><code>#Random Forrest with ranger function
gso.fire.filtered.rf = gso.fire.filtered %&gt;%
  dplyr::select(response_time_seconds,TotalStaffOnIncident , FireDistrict , DayOfWeek , 
           shift , Month , AlarmTime , NatureCode)

RF.Mod.Ranger &lt;- ranger(response_time_seconds~TotalStaffOnIncident + FireDistrict + DayOfWeek + 
                         shift + Month + AlarmTime + NatureCode,
                       data = gso.fire.filtered.rf[complete.cases(gso.fire.filtered.rf),], importance = &quot;impurity&quot;, num.trees = 500)

variable = names(RF.Mod.Ranger$variable.importance)
rf.vIMP.df = data.frame(variable = variable, vIMP = RF.Mod.Ranger$variable.importance)

ggplot(rf.vIMP.df, aes(x=reorder(variable,vIMP), y=vIMP,fill=variable))+ 
  geom_bar(stat=&quot;identity&quot;, position=&quot;dodge&quot;, show.legend = FALSE)+ coord_flip()+
  ylab(&quot;Variable Importance&quot;)+
  xlab(&quot;&quot;)+
  ggtitle(&quot;Information Value Summary&quot;)</code></pre>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
