---
title: "Statistical Analysis of Fire Incidents"
author: "Danielle Mirzaeian, Nahom Fisseha"
date: '2022-06-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading necessary packages

```{r}
library(readr)
library(lubridate)
library(ggplot2)
library(dslabs)
library(dplyr)
library(ggrepel)
library(ggthemes)
```

## Loading the dataset
```{r}
gso.fire <- read_csv("Greensboro_Fire_Incidents.csv")
```

next code will appear after this

## Filtering for incidents prior to June 1st 2022
```{r}
gso.fire = 
  gso.fire %>%
  mutate(AlarmDate2 = make_date(Year, Month, Day)) %>%
  filter(AlarmDate2 < '2022-06-01')
```

## Filter for property type 1-2 family dwellings
```{r}
gso.fire = gso.fire %>%
  filter(PropertyUse == '419 - 1 or 2 family dwelling')
```

## Convert to call process time to seconds and add to gso.fire
```{r}
gso.fire = gso.fire %>%
  mutate(call_process_period = lubridate::hms(CallProcessingTime), 
         call_process_seconds = period_to_seconds(call_process_period))
```

## Convert response time to seconds and add to gso.fire
```{r}
gso.fire = gso.fire %>%
  mutate(response_time_period = lubridate::hms(ResponseTime),
         response_time_seconds = period_to_seconds(response_time_period))
```

## Convert total response time to seconds and add to gso.fire
```{r}
gso.fire = gso.fire %>%
  mutate(total_response_period = lubridate::hms(TotalResponseTime),
         total_response_seconds = period_to_seconds(total_response_period))
```

